### ISSUE TITLE
Changing Draggable.vars.type after startup has no effect!

### ISSUE THREAD

**Issue by Glidias** [greensock/GreenSock-JS#100]
Documentation could provide a list of which parameter variables only work on setup, and provide fallback methods for those people that wish to re-update those variables on the fly. I had to create my own makeshift this.setType fallback public method for this.

**Comment by jackdoyle** [comment]
Hm, I wouldn't really recommend a setType() method. There are a lot of things tied to the type of Draggable, and it's not very practical to mess with that after it's created. My recommendation would be to create a new Draggable instance of that different type instead. As for a list of fallback methods, I'm not entirely sure what you mean - are you looking for something beyond what is provided in the API docs? The configuration properties that you pass into the create() method aren't really intended to be persistent or available for changing after creation. I'd recommend using the regular properties and methods that are documented.
