### ISSUE TITLE
Can I use tweenlite in cocos2d-js?

### ISSUE THREAD

**Issue by haroel** [greensock/GreenSock-JS#101]
cocos2d-js is a js game engine，but is not good to make animation , , when I write as3.0 ,I always use tweenlite to make high quality animation。 
 I want to use tweenlite in my cocos2d-js project， how can I do it?

**Comment by jackdoyle** [comment]
I'm not familiar with cocos2d, but I do know that GSAP can animate any numeric property of any JavaScript object, so I can't imagine you'd have any trouble using it for pretty much any animation task. Hit us up in the forums if you have any specific questions. http://greensock.com/forums/. Happy tweening!
