### ISSUE TITLE
Draggable.js with facebook's react.js

### ISSUE THREAD

**Issue by oozaa** [greensock/GreenSock-JS#105]
Hi,
I am  writing new mobile hybrid app and using react.js + GSAP(Draggable.js). Had a problem making both working nicely together as react.js adds on elements empty callbacks(for example element.onclick=function emptyFunction() {return false } ). 

In GSAP Draggable.js is used _isClickable() (utils/Draggable.js line 844) to check is element clickable by checking is e.onclick is setted. And this check  fails because react.js setts emptyFunction() for all elements if there is setted onTouchStart attribute. 

I made ugly hack to fix this issue  by checking like that - (e.onclick && !e.onclick.thatReturns), but it's ugly and I will not sleep calm. 
I am wondering is there is any other way to solve this issue? May you could recommend better solution? 

Thanks!

**Comment by jackdoyle** [comment]
Nice to see that you're using Draggable with React. We'd love to hear how that goes for you. More and more people seem to want to do that these days. 

In more recent versions of Draggable, you can actually define your own function to do the clickability testing, totally circumventing Draggable's default logic. Just define it in the vars object, like:
```javascript
Draggable.create("#yourID", {
    type:"x,y",
    clickableTest:function(element) {
        //your logic here. Return true or false as you see fit.
    }
});
```
Or you could add data-clickable="true" or data-clickable="false" to your element(s) in the markup. Lots of options :)

Does that help?

**Comment by oozaa** [comment]
That is great! End it up by using clickableTest. I don't know how I missed this as I was checking documentation multiple times. My mistake!

And GSAP(TweenMax+Draggable) together with React, TransitionGroup, FLUX works well! It is so nice to build mobile hybrid app that has smooth transitions. Anyway still can't achieve good performance on older phones like Galaxy S3, iPhone 4s. But that is not my target audience so screw them  :smile:
