### ISSUE TITLE
Broken rotationY/rotationX in non-Chrome browsers in 1.17.0 from Bower

### ISSUE THREAD

**Issue by ilyashubin** [greensock/GreenSock-JS#109]
With TweenMax 1.17.0, which I got from bower, I can't make it rotate things around its axis - `rotationY`/`rotationX`, at least for SVG elements (I tested on `g` elment), while version from Cloudflare CDN do it well.
I tested on code from this pen: http://codepen.io/shu_ilya/pen/waLqjz (this is working example) - bird at the top must rotate around its y axis, if I use bower version - nothing happens. Check it out please

EDIT: it seems that problem in 1.17.0 version itself (even from Cloudflare CDN), if I use 1.17.0 on CodePen it work though, so I can reproduce this only on my localhost or file://. With 1.16.1 all works fine

**Comment by jackdoyle** [comment]
I'm a bit confused - the SVG spec doesn't support 3D at all. Technically Chrome does support it if it's applied via a CSS style, but most other browsers don't (and won't). I'd strongly recommend avoiding 3D in SVG.

**Comment by ilyashubin** [comment]
Oh, sorry, didn't know that! Just read that SVG 2.0 will support 3d transforms, so some browsers already implemented this. Thanks for explanation.
