### ISSUE TITLE
delete that please

### ISSUE THREAD

**Issue by mib32** [greensock/GreenSock-JS#110]
That was the question better belonging to forum i guess.

**Comment by jackdoyle** [comment]
This is a great question to post in the forums at http://greensock.com/forums/ rather than creating a github issue. 

To answer your question, I'd recommend animating the "x" transform rather than the background-position-x so that it can benefit from GPU acceleration.

Happy tweening!

**Comment by mib32** [comment]
@jackdoyle thanks. I actually edited the post because two seconds after i wrote this i understood that better place is indeed the forums. i'll restore it if you like
