### ISSUE TITLE
GSAP set(), roundProps and floating point values

### ISSUE THREAD

**Issue by oozaa** [greensock/GreenSock-JS#112]
Element in css file has rule 
```
transform:translate(-50%, -50%);
``` 

When this element appears in DOM I simple set new values 
```
GSAP.set(node,{
  scaleX: 0.7, 
  scaleY: 0.7
});
```
After some action I animate the same node:
```
GSAP.to(node,0.7,{
  scaleX: 1, 
  scaleY: 1
});
```
Issue: because in css file there is rule -50%, -50% GSAP calculates x and y end values with floating point (x:150.5, y:190.5) and I get blurry elements like input boxes. I want to simply round  these values to have integer. Currently every time after GSAP.set() I do silly hack like this one  and it solves it. 
```
if(node._gsTransform.x%1 || node._gsTransform.y%1){ 
  GSAP.set(node,{
    x: Math.floor(node._gsTransform.x),
    y: Math.floor(node._gsTransform.y)
  });
}
```
I am looking for a better solution.

**Comment by jackdoyle** [comment]
It's always best to set transforms through GSAP rather than a hybrid of CSS and GSAP. The browser reports the values as a matrix() or matrix3d() without any percentages (it's not GSAP that's doing that calculation or ripping out percentages). It's even fine to set something initially with CSS but then when the page loads, set it [again] with GSAP just so that it can calibrate itself properly and understands that you want percentages. For example, TweenLite.set(...{xPercent:-50, yPercent:-50})

Does that help at all?

**Comment by oozaa** [comment]
Thanks for reply , it make sense for sure. What I really want that GSAP would take matrix() data from browser as it reports it without percentages and would let me run values through some filter to Math.floor values that browser reported to it. 
Let me explain why I want something like that.  Setting in CSS transform:translate(-50%,-50%);  or in GSAP (xPercent:-50, yPercent:-50) will use percentages. My elements width and height are based on their child elements. I can't be sure that browser will not render everything blurred because 50% sometimes will return .5 values so I just want to floor it and force to be crisp. Using -50% -50% in CSS is very easy way to H and V center elements and it is very cool, but sadly it has this very well know side effect of .5 values...

For now I will wrap GSAP.set() to my own function to always check for .5 case. But I would be very happy that I could set some global filter for GSAP and keep using not wrapped functions. I hope my case make sense.

**Comment by jackdoyle** [comment]
Yeah, I don't see a performant way to add this kind of functionality into the core and it certainly seems like an edge case. Since you already have a solution that works with the existing API, I'm not inclined to pursue it much further but if you have any other ideas feel free to share.
