### ISSUE TITLE
onComplete called twice when reusing fromVars or toVars

### ISSUE THREAD

**Issue by AlexGalays** [greensock/GreenSock-JS#113]
Just had the most obscure and annoying bug after refactoring something completely unrelated (or should be) to gsap.

See the bug here (using the latest master code):  https://jsfiddle.net/43pdzvmL/
both 'complete' callbacks are printed twice (the first lot being called immediately, it seems).

What's crazy is that if I do not reuse the `fromVars` and `toVars` objects and instead inline their values then it works fine:  https://jsfiddle.net/b2to0rdt/

That tells me gsap is either mutating the params object I give it or assume something about their reference equality, etc; Something it absolutely shouldn't do.

Cheers

**Comment by AlexGalays** [comment]
A public API shouldn't delete things from an object passed to it:  https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenLite.js#L904

Could do args = copy(args)  if under the condition where it must be updated for internal use.

**Comment by jackdoyle** [comment]
I'm really sorry to hear about the frustration Alex. I totally see what you mean and in general I COMPLETELY agree with you. However, this is a very tricky situation that's not easily solved with your suggestion. 

The object you pass in as the vars parameter gets attached to the tween, thus if we copy() the original object and use that instead, then that's no longer true (tween.vars !== originalParam). We could create an additional copy that we reference separately internally (leave the original at tween.vars but use this new copy for our actual work inside the tween) but that has a bunch of other side effects like:

- creating an additional object for every tween with redundant data (memory footprint expands)
- we must update a bunch of other chunks of code that are pointing to the tween.vars and can no longer use that as a "source of truth". Consequently, if something changes on that object (like if the onComplete is changed), it wouldn't flow through to the alternate/copy source of truth we're now using internally

We also lose the performance benefit of doing that conversion ONCE on the object and then being able to reuse that elsewhere. For example, if you pass that same vars object to multiple tweens, it'd get sanitized/reformatted once by the first tween and all the others wouldn't have to do it again. 

I'm not saying the current behavior is "right" and your suggestion is "bad" or anything. I think both have merit. I just tend to put a heavy emphasis on performance optimizations and reducing memory usage if possible, but there's definitely a trade-off in situations where you're trying to use that object in other ways and aren't mindful of what GSAP does in this one special case where the target is a DOM element and you're animating CSS properties (and of course we're doing this as a convenience...the original version didn't do it at all). 

I appreciate the you letting us know about the frustration and offering a suggestion. If you've got any other advice I'm all ears.

**Comment by AlexGalays** [comment]
In the meantime I settled for using constant objects (to keep things dry between the enter animation and the exit one) but then copy these constants every time I create a tween so the original don't get mutated.
It seems the current module heavily depend on the assumption of mutable arguments; Should it then be explained in the documentation?

**Comment by jackdoyle** [comment]
Thanks for the update. And yeah, if you see any specific place in the docs that you think a note like this belongs, just let us know.
