### ISSUE TITLE
Cannot create webjar - licence info missing

### ISSUE THREAD

**Issue by evertp** [greensock/GreenSock-JS#115]
Tried to create a webjar of this lib at http://www.webjars.org/bower but got the error:

````
Failed! Could not get license
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: gsap
````

I presume adding the licence field to bower.json resolves the problem.

**Comment by jackdoyle** [comment]
I added a "license" field. I hope that helps.
