### ISSUE TITLE
Timeline events, .tweenTo(), and floating point precision.

### ISSUE THREAD

**Issue by alec-mccormick** [greensock/GreenSock-JS#116]
I've noticed this issue while working on a site for a client. When a timeline's duration ends in something like .9 repeating or a trailing .0000000001, events don't properly fire tweening to that time.

Here is a JS Fiddle to demonstrate the bug: https://jsfiddle.net/4mf4zgyf/1/

Note that the 2nd 'onComplete' event doesn't fire until the button is clicked for a 3rd time.

I addressed this issue by changing certain animation times to numbers more easily represented as powers of 2 (changing 2.61 seconds to 2.609375) as seen here: https://jsfiddle.net/zk4p5yg6/1/ but some internal rounding would resolve the problem (or possibly the ability to represent animation times as milliseconds instead of seconds).

**Comment by jackdoyle** [comment]
Ah, very interesting...and exceedingly rare. We'll put a workaround into the next release. Thanks for pointing this out. 

(By the way, switching to milliseconds wouldn't help this at all)

**Comment by alec-mccormick** [comment]
I figured, thanks for looking into it!

**Comment by jackdoyle** [comment]
This should be fixed in the latest release. 

Happy tweening!
