### ISSUE TITLE
jspm install, can't seem to use / import Draggable

### ISSUE THREAD

**Issue by tgienger** [greensock/GreenSock-JS#117]
I'm not entirely sure how to import gsap properly. I used `import TweenMax from 'greensock'` for a while until I realized it didn't matter what I imported I was always getting the same thing as `import 'greensock'`. It seems the only thing I don't have access to is Draggable. 

I modified the `GreenSock-JS@1.18.0.js` file in attempt to include Draggable, but then it couldn't find TweenLite  :/

Using jspm / System.js - still learning it.

**Comment by jackdoyle** [comment]
Sorry, we're not familiar with jspm/system.js. Let us know if there's something specific that you need us to do on our end.

**Comment by baptistebriel** [comment]
@tgienger what you could use is the `browser` field in your `package.json`:

```javascript
"browser": {
    "Draggable": "./shims/gsap/src/uncompressed/utils/Draggable.js"
    // etc...
}
```

**Comment by tgienger** [comment]
Sorry I haven't replied sooner. I'm in the hospital with my wife while she recovers from surgery. I'll do some exploration and try the shim out when I get home and start messing with it again. Thanks for the help!
