### ISSUE TITLE
gsap plugins with webpack

### ISSUE THREAD

**Issue by geddski** [greensock/GreenSock-JS#118]
I'm using webpack with Greensock. I'm able to npm install gsap, and require() it with webpack. I need to do the same thing for Draggable, but it doesn't appear to be a part of the gsap module.

**Comment by jackdoyle** [comment]
Sorry, we're not very familiar with WebPack and we're super busy working on some exciting new features. I wonder if maybe you just pointed at the wrong file/directory? Remember, Draggable is in the /utils/ directory.

**Comment by pospi** [comment]
You just need to use the relative path within the GSAP module to load the Draggable file:

`require('gsap/src/uncompressed/utils/Draggable');`

**Comment by jackdoyle** [comment]
Thanks @pospi
