### ISSUE TITLE
Draggable - stuttering issue on touch-based browsers

### ISSUE THREAD

**Issue by conrad-vanl** [greensock/GreenSock-JS#120]
Ran into an interesting issue when upgrading our version of Draggable from 0.12.0 to 0.14.0. On touch-based browsers I am experiencing a horrible stutter effect when dragging, that is 'fixed' when altering lines 1521-1527 in Draggable.js back to where they were in version 0.12.0...

Changing these lines:

````javascript
if (allowNativeTouchScrolling || self.autoScroll) {
	_recordMaxScrolls(target.parentNode);
}
if (self.autoScroll && !rotationMode && !scrollProxy && target.parentNode && !target.getBBox && target.parentNode._gsMaxScrollX && !_placeholderDiv.parentNode) {//add a placeholder div to prevent the parent container from collapsing when the user drags the element left.
	_placeholderDiv.style.width = (target.parentNode.scrollWidth) + "px";
	target.parentNode.appendChild(_placeholderDiv);
}
````
https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/utils/Draggable.js#L1521

to:

````javascript
if (self.autoScroll && !rotationMode && !scrollProxy && target.parentNode && !target.getBBox) {
  _recordMaxScrolls(target.parentNode);
  if (target.parentNode._gsMaxScrollX && !_placeholderDiv.parentNode) { //add a placeholder div to prevent the parent container from collapsing when the user drags the element left.
    _placeholderDiv.style.width = (target.parentNode.scrollWidth) + "px";
    target.parentNode.appendChild(_placeholderDiv);
  }
}
````

https://github.com/greensock/GreenSock-JS/blob/39717362f80c311c4f7889353b5c928acc624d80/src/uncompressed/utils/Draggable.js#L1297

Here is a video example of the issue I'm experiencing. I can re-create it both on mobile safari and in Chrome with device mode emulation enabled: https://drive.google.com/file/d/0B5rxBKub1xXvZm0wbXpDMjhvYzg/view?usp=sharing

**Comment by conrad-vanl** [comment]
After some experimentation in a JSBin, it appears this happens when there are nested draggable elements -

http://output.jsbin.com/xocugidama
(make sure to try this example on a touch-enabled browser - verified on mobile safari and in Chrome with device mode emulation set to an iphone 6)

Previously this was working okay without stutter - you can try that about by changing the GSAP versions in the jsbin to 0.16.0

**Comment by jackdoyle** [comment]
Did you try setting allowNativeTouchScrolling to false? Like:
```javascript
Draggable.create(..., {allowNativeTouchScrolling:false, ...});
```

**Comment by conrad-vanl** [comment]
Initially testing `allowNativeTouchScrolling` in the JSBin seems to fix it, will test in our app a little later. How does this affect nested draggables like this?

**Comment by jackdoyle** [comment]
The native touch scrolling feature tells Draggable not to preventDefault() on the native event so that users can natively scroll in one direction (Draggable senses that direction). It sounds like the jerkiness in your situation is the native scrolling. So turning it off basically just tells Draggable to do its thing and not worry about native scrolling at all. Some people really wanted native scrolling when it's in the opposite direction of a directionally-restricted Draggable.

**Comment by conrad-vanl** [comment]
@jackdoyle confirmed; `allowNativeTouchScrolling: false` does fix this issue. Thanks!
