### ISSUE TITLE
`allowEventDefault: true` and `<input type="date" />`

### ISSUE THREAD

**Issue by conrad-vanl** [greensock/GreenSock-JS#122]
While it seems to be undocumented, we have been utilizing the `allowEventDefault` parameter in combination with `dragClickables` set to true to give us the ability to both drag and interact with clickables within a draggable object. For example, forms. 

For the most part, this works rather well - can select text in inputs, etc. However, we have noticed that the `<input type="date" />` element (and probably other similar html5 field types) are not fully functioning (atleast in chrome). On Chrome, you are unable to open up the native date calendar when clicking on the field or trying to click the field's added drop down button, as well as chrome's "clear" button on the input doesn't seem to work.

Here is an example codepen: http://codepen.io/anon/pen/VvbrXw/

If you remove `dragClickables` + `allowEventDefault` from the options passed to Draggable, the date input works fully again.

**Comment by jackdoyle** [comment]
This should be resolved in the latest update. Thanks for pointing it out!
