### ISSUE TITLE
Setting an initial delay property on staggerFrom / staggerTo

### ISSUE THREAD

**Issue by nickspiel** [greensock/GreenSock-JS#124]
Currently there is no way to set an initial delay on staggerTo / staggerForm objects. The delay specified only effects the amount of delay between objects in the collection.

It would be amazing if there was a way to set an initial delay (and be able to use labels and 'label-=3').

**Comment by jackdoyle** [comment]
Absolutely - that's already baked in. I'm not sure if you're using TweenMax or one of the timeline classes, so I'll show you both: 
```javascript
TweenMax.staggerTo(elements, 1, {x:100, delay:2}, 0.01);

// - OR -

var tl = new TimelineLite();
tl.staggerTo(elements, 1, {x:100, delay:2}, 0.01);

// - OR -

var tl = new TimelineLite(); 
tl.staggerTo(elements, 1, {x:100}, 0.01, "label+=3");
```

Is that what you're looking for?

**Comment by nickspiel** [comment]
That is exactly what I am after! Thanks!!!
