### ISSUE TITLE
Multiple .from() calls don't behave correctly

### ISSUE THREAD

**Issue by GetContented** [greensock/GreenSock-JS#125]
If you chain to calls to *from()* on an item, becuase of the way *from()*s are implemented (as reversed *to()*), strange behaviour manifests.

Our designer expected to be able to make two subsequent identical calls to *from()* on an element and have the same behaviour manifest, but instead, because the implementation of from is that the animation is simply run in reverse, the second *from()* animation doesn't do anything at all, it just stays in the same position: this is because the framework seems to see the from position and to position as identical.

I'm assuming this could be worked around by setting the "current position" internally to be the actual position after it has been animated the first time (it seems to "think" the item is at the from position when it's not).

**Comment by jackdoyle** [comment]
I think you might just be misunderstanding the default behavior. By default, a from() tween will *IMMEDIATELY* set the "from" values regardless of how much of a delay there is until the actual tween commences. This is the behavior most people expect. If you're doing multiple from() tweens on the same element, it'll start at whatever the last from() was called. 

You can set immediateRender:false to avoid that. I assume that'll solve things for you. Also remember that you can use a fromTo() which allows you to set both the from and to values. 

```javascript
timeline.from(... {x:0})
    .from(... {immediateRender:false, x:100});
```

**Comment by GetContented** [comment]
I don't know what you mean by "it'll start at whatever the last from() was called". What does "at" mean in that sentence? Do you mean "at the time that the last from() was called", or "at the position when the last from() was called"?

I'd expect calling from() with the same values and durations on the same object twice in a row to repeat the animation. I'll get our designer to try the immediateRender:false option you suggest. If this solves his problem, then I'll close this.

**Comment by jackdoyle** [comment]
Yep, immediateRender:false should do the trick. But if you're just looking to repeat the same behavior twice, it'd probably be simpler to just add repeat:1 to a single tween. 
```javascript
timeline.from(..., {x:100, repeat:1});
```
(Just make sure you've got TweenMax loaded so that "repeat" works)
