### ISSUE TITLE
Update bower.json main to include both tweenmax and timelinemax

### ISSUE THREAD

**Issue by mindfullsilence** [greensock/GreenSock-JS#128]
Doesn't it make more sense to list out more than just the TweenMax.js script as the main file in the bower.js? 

```
{
    "name": "gsap",
    "version": "1.18.0",
    "description": "Think of GSAP as the Swiss Army Knife of animation...",
    "author": {
        "name": "Jack Doyle",
        "url": "http://greensock.com/gsap/"
    },
    "main": [
        "./src/uncompressed/TweenMax.js",
        "./src/uncompressed/TimelineMax.js"
    ],
    "dependencies": {

    },
	"ignore": [],
    "repository": {
       "type": "git",
       "url": "https://github.com/greensock/GreenSock-JS" 
    } 
}
```

**Comment by jackdoyle** [comment]
Is that even allowable? I figured there had to be only 1 "main" file (otherwise what's the point of "main") :) But I'm admittedly not very familiar with bower or its conventions.

**Comment by mindfullsilence** [comment]
Absolutely. You can see an example here from the bower docs: 
https://github.com/bower/spec/blob/master/json.md#main

You could honestly put all the plugin and easing files in main if you wanted to. 

"main" really just defines the files which make up the unique modules. It's not really used for anything internal to bower, but is helpful when all someone wants is the developments files by using tools such as this:
https://github.com/blittle/bower-installer
Which looks at the "main" property in the repo's bower.json file and only pulls those files, rather than the entire repo.

**Comment by jackdoyle** [comment]
Hm, the docs you linked to say "Only one file per filetype." so wouldn't we be violating that if we had multiple .js files?
