### ISSUE TITLE
Can't start new TweenMax after TweenMax.killAll(true)

### ISSUE THREAD

**Issue by fdev** [greensock/GreenSock-JS#129]
After I call `TweenMax.killAll(true)`, with first parameter `complete` having the value `true` so all tweens will complete, I'm unable to start another TweenMax on the objects whose tweens were killed.

I've created an example to demonstrate the issue on http://jsfiddle.net/5c9zjr6m/.

When the first parameter of `TweenMax.killAll()` is set to `false`, I *can* start a new TweenMax, but the starting positions are all wrong.

**Comment by jackdoyle** [comment]
That's not a bug - you tweened to rotation:360, thus the next time you try tweening to 360, there's nowhere to tween (it's already 360). See what I mean?
