### ISSUE TITLE
Increase background position infinetly

### ISSUE THREAD

**Issue by kamijoutouma** [greensock/GreenSock-JS#135]
So this is my code
`TweenMax.to(crack, 15, {backgroundPosition:i+"px", repeat:-1, ease:Linear.easeNone, onComplete: function(){i++;}});`
This however doesn't work. I'm trying to move a background image to the right infinitely (its size is set to "contain" so i have no image width to work with, if i did i would set the position to that)

Is there a way to make the background position increase infinetly / does doing so put strain on the users cpu.

JSfiddle https://jsfiddle.net/KamijouTouma/mhya7mrk/31/ all it does is keep going back and forth from 1 to 0.

**Comment by jackdoyle** [comment]
That's the correct behavior - it wouldn't be a true "repeat" if it was going to new values every time. But it's pretty easy to get the effect you're after - just use a recursive function like:
```javascript
var i = 0; 
function moveBG() {
    i++;
    TweenMax.to(crack, 0.5, {backgroundPosition:i + "px", ease:Linear.easeNone, onComplete: moveBG});
}
moveBG();
```

By the way, the best place for questions like this is in the forums at http://greensock.com/forums/. There are a lot of active members there that are great at not only answering things like this quickly, but also offering different approaches. It's a great place to learn even if you never ask a question. 

Happy tweening!

**Comment by kamijoutouma** [comment]
Just for others to note. To make this killable.

```js
var crack = document.getElementById('crack'); 
var i = 0;
var lol = {}
function moveBG() {
	i++;
 	lol.crack = TweenMax.to(crack, 0.02, {backgroundPosition:i + "px 50%", ease:Linear.easeNone, onComplete: moveBG});
};
moveBG();

setTimeout(function(){
	lol.crack.kill();
},5000);
```
