### ISSUE TITLE
How to require just TweenLite & TimelineLite when using browserify

### ISSUE THREAD

**Issue by samjbmason** [greensock/GreenSock-JS#137]
I'm having some issues trying to setup TweenLite & TimelineLite in my setup. Im using browserify and Im trying to require it like so 

````
var TweenLite = require('./TweenLite.js')
var TimelineLite = require('./TimelineLite.js')

let masterTL = new TimelineLite({
    onComplete:function() {
      this.restart();
    }
  })
...
````

I can confirm they are being included in the bundle but for some reason my code just isnt running, there are no errors showing in the console.

Im not using the minified versions either, if thats of any help. If i install TweenMax then it works as expected but I would ideally like to keep my js file size small.

**Comment by jackdoyle** [comment]
Hm, it's tough to say without seeing your files, but I wonder if maybe you're trying to animate CSS-related properties and that's why it's not working. TweenMax includes CSSPlugin **inside** of it, but TweenLite doesn't have that so you'd need to load that separately if you want CSS-related animations to work. But if all you're doing is that code that you shared (a TimelineLite that does absolutely nothing except restart itself upon completion), I'm baffled and would love to see a sample file.

**Comment by samjbmason** [comment]
Ah sorry no Im doing more than just restart a timeline this is the full code, I didnt think I had to use the CSS plugin as I was simply changing svg attributes

````
import $ from 'jquery'
import Tween from './TweenLite.js'
import Timeline from './TimelineLite.js'

let logo = function() {
  let eyes = $('.eye')
  let eyeLids = $('.eyelid')
  let masterTL = new Timeline({
    onComplete:function() {
      this.restart();
    }
  })

  let blink = function() {
    let tl = new Timeline()
    tl.set(eyeLids, {y:14}, '+=0.4')
    tl.set(eyes, {opacity:0})
    tl.set(eyeLids, {y:0}, '+=0.2')
    tl.set(eyes, {opacity:1})
    return tl
  }


  masterTL
  .to(eyes, 0.2, {x:-15}, '+=1.2')
  .add(blink())
  .to(eyes, 0.2, {x:0}, '+=0.4')
  .add(blink())
  .add(blink())
  .to(eyeLids, 0.2, {y:-6, scaleX:0.91, transformOrigin:'right top'}, '+=1.5')
  .to(eyeLids, 0.2, {y:0, scaleX:1}, '+=1')
  .to(eyes, 0.2, {x:18}, '+=1.5')
  .to(eyes, 0.3, {x:-15}, '+=1.5')
  .to(eyes, 0.2, {x:0}, '+=1.5')
  .add(blink())
````

**Comment by jackdoyle** [comment]
Ah, that explains it. To animate those SVG properties, you do indeed need CSSPlugin (which, again, is inside TweenMax). All the magic that handles transforms on DOM elements is in CSSPlugin. I bet you'll see that your stuff works fine once you load that along with TweenLite. Let us know if you run into any other problems. Happy tweening!

**Comment by samjbmason** [comment]
I just added `CSSPlugin` and switched out TweenMax to use `TweenLite` instead but now Im getting this error.

`Error: Cannot find module '../TweenLite.js'`

**Comment by jackdoyle** [comment]
Sounds like you just need to make sure you've got TweenLite and CSSPlugin in the correct directories in relation to one another. Remember, we put plugins into a directory deeper (a "plugins" folder).

**Comment by samjbmason** [comment]
so this is my folder structure and Im importing from the file `logo.js`

<img width="159" alt="screen shot 2016-01-27 at 21 03 45 1" src="https://cloud.githubusercontent.com/assets/878503/12628121/873199c2-c539-11e5-8434-ea59c11c2c3e.png">

**Comment by samjbmason** [comment]
Never mind got it working. Like you said it needs to be in the correct folders :+1:
