### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by salzhrani** [greensock/GreenSock-JS#138]
curious to know the owners' stance on updating the codebase to es6/2015? it has a number of benefits like leveraging the user's build process to produce a smaller build. I have started to hack on it [here](https://github.com/salzhrani/GreenSock-JS/commits/es6) and could not continue confidently without some tests to prevent regressions.

**Comment by jackdoyle** [comment]
We do plan to explore ES6 refactoring soon but can't commit to a specific release date. It will likely be a v2.0.0 release because it'll involve some sweeping changes to the guts. We're excited about the ES6 possibilities. Thanks for asking :)
