### ISSUE TITLE
TypeScript - Add TypeScript Support

### ISSUE THREAD

**Issue by deinok** [greensock/GreenSock-JS#140]
Add a TypeScript Declaration Files

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/greensock/greensock.d.ts

**Comment by jackdoyle** [comment]
With the ES6 movement, do you think TypeScript is much of a factor? At this point, we don't plan to _officially_ support TypeScript, but if anyone wants to tackle creating declaration files, please let us know and perhaps we can link to them.

**Comment by OSUblake** [comment]
TypeScript is a superset of JavaScript, much like SASS is to CSS, so it's really doesn't compete with ES6 as any valid JavaScript is valid TypeScript. One of the biggest reasons for using TypeScript is the improved tooling it provides (type checking, refactoring, auto-complete). 

I don't see TypeScript going away anytime soon. It's going to popular with MS devs, Angular 2, NativeScript, and game developers. One of these days I'll be able to finish the definitions I originally started on. If anybody needs definitions for Draggable, here's a [gist](https://gist.github.com/OSUblake/d8a098279d7e251eef6d) based on an older set of definitions that I was working on. Let me know if there are any problems with them.
https://gist.github.com/OSUblake/d8a098279d7e251eef6d
