### ISSUE TITLE
onReverse event

### ISSUE THREAD

**Issue by glebmachine** [greensock/GreenSock-JS#144]
Hi guys!

Please, add `onReverse` (or `onReverseStart`) event to timeline.

**Comment by jackdoyle** [comment]
Please see:
http://greensock.com/forums/topic/9182-detect-reverse-start-event/?p=36998
-and-
http://greensock.com/forums/topic/10966-onreversestart-still-dont-understand-why-not/#entry44006

Perhaps you could help me understand why this would be helpful, like a practical use case that couldn't be accomplished by simply dropping some code into wherever you are calling reverse() (as that's where it'd start)?

**Comment by glebmachine** [comment]
I have pretty clear reason.

When we play forward we've got:
- [X] onStart 
- [X] onComplete

When we play backward we've got:
- [ ] onReverseStart
- [X] onReverseComplete

It looks weird, isn't it?
Here we have to choose one of following options:
1 - `onReverseStart` is overengineering, then we should remove `onStart` (for the same reason)
2 - `onStart` is strongly required because we need to have option to detect `when animation start`. So, following this logic further, we need this `onReverseStart` event.

**Comment by glebmachine** [comment]
Excuse me, any news here?

**Comment by jackdoyle** [comment]
No, not really. As much as I totally see your logic and why you'd want it included, I'm having a really hard time justifying the performance hit given how infrequently a feature like this would actually be used out in the wild. In other words, 100% of users would pay the price of the extra conditional statement in **every** render of **every** tween just so that 0.001% of users could define an onReverseStart. If enough people request this, however, I'll reconsider.

**Comment by HamidReazaNikoonia** [comment]
hi guys

i think this feature very helpful for developer , please add this feature
because in many case we have fire an action quickly when reverse happening 

thanks

**Comment by quadlayers** [comment]
+1

**Comment by jackdoyle** [comment]
I just added a helper function to the docs that gives you onReverse functionality plus a whole lot more. See https://greensock.com/docs/v3/HelperFunctions#onReverse

Does that help? 

The nice thing about this is it keeps the core lightweight and doesn't require extra processing on the vast majority of animations that don't need this functionality.

**Comment by quadlayers** [comment]
thanks @jackdoyle !

**Comment by ethanmay** [comment]
Thanks @jackdoyle I am finding this all these years later and it's very helpful.
