### ISSUE TITLE
[bug?] how was yoyo ,reapeat and reapeatDelay work??

### ISSUE THREAD

**Issue by twobear** [greensock/GreenSock-JS#145]
today ,I wrote a Heartbeat Animation with " yoyo" ,"reapeat" ,"reapeatDelay" ,and the effect looks like BUG..？
In my impression ,it shuld work like : 
[yoyo]-[reapeatDelay]-[yoyo]-[reapeatDelay]...
1-2-3-2-1-reapeatDelay-1-2-3-2-1-reapeatDelay-....
but in fact:
 -1-2-3-reapeatDelay-3-2-1-... -1-2-3-reapeatDelay-3-2-1-
that's strange.
code:
 `   var tl2=TweenMax.fromTo(arr[1],.5,
            {
                scale:1.2
            },
            {                scale:1,
                yoyo:true,
                ease:Expo.easeOut,
                repeat:-1,
                repeatDelay:1
            },.5).play();`
demo: https://jsfiddle.net/1m9z3z4k/4/

**Comment by jackdoyle** [comment]
Nope, that's not a bug at all. It's exactly the way it's supposed to work, and it can be very useful indeed. Remember, yoyo simply describes the direction of the repeat. So the delay should occur between each repeat (regardless of direction). It sounds like you're conceptually grouping the yoyo action in with the initial animation. You could certainly get the effect you're after by just putting a yoyo-ing TweenMax tween (with no repeatDelay, and only one repeat) inside of a TimelineMax that has a repeatDelay applied.
