### ISSUE TITLE
tweening x or y using transform actually changing z-index = 0

### ISSUE THREAD

**Issue by kambing86** [greensock/GreenSock-JS#146]
```javascript
TweenMax.fromTo(currentSlide, 0.8, {
  x: (100 * direction).toString() + "%"
}, {
  x: "0%",
  onComplete: function() {
    currentSlide.css({
      transform: "",
      "z-index": ""
    });
  }
});
```

should we fix it by reverting all the styles applied to the element?

**Comment by jackdoyle** [comment]
That's true in Safari and it's very purposeful - it works around a bug in some old versions of Safari that would cause things not to render properly unless a z-index was set. Weird, I know. But again, this is actually GSAP trying to help you; it's not a bug. GSAP should only apply that if there is no z-index already set. In other words, it doesn't always force it to 0 - it just sets it to 0 if there isn't anything set at all.
