### ISSUE TITLE
Karma Errors

### ISSUE THREAD

**Issue by anthonygreco** [greensock/GreenSock-JS#149]
Looks like version 1.18.5 introduces the following error when I run my Karma tests now:

```
26 05 2016 09:53:13.642:WARN [web-server]: 404: /base/assets/TweenLite.js
26 05 2016 09:53:13.643:WARN [web-server]: 404: /base/assets/plugins/CSSPlugin.js
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR: 'There is no timestamp for /base/assets/TweenLite.js!'
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR: 'There is no timestamp for /base/assets/plugins/CSSPlugin.js!'
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR
  Error: Script error for "../TweenLite", needed by: draggable
  http://requirejs.org/docs/errors.html#scripterror
  at /node_modules/requirejs/require.js:140
```

Still looking into what changed...

**Comment by jackdoyle** [comment]
That kinda sounds like just a path error. Like perhaps you've got TweenLite (or Draggable) in the wrong directory? Remember, Draggable is inside a "utils" folder whereas TweenLite isn't - that's why it points to "../TweenLite.js" from inside Draggable.
