### ISSUE TITLE
New version 1.18.5 is not compatible with r.js of requirejs?

### ISSUE THREAD

**Issue by ibio** [greensock/GreenSock-JS#152]
Hi, I am using r.js of requirejs to compress my project. I noticed this version has changed `define(["../TweenLite"], getGlobal);` (line 2769 of CSSPlugin.js), you added ../ and I cannot compile it anymore because the config using in r.js is not a relative system.

```
//this is my config
paths: {
  app: '../app',
  jquery: 'jquery-2.2.4.min',
  lodash: 'lodash.min',
  underscore: 'lodash.min',
  backbone: 'backbone-min',
  bootstrap:'bootstrap-3.3.5-dist/js/bootstrap.min',
  typed:'typed.min',
  columnize:'jquery.columnize',
  //NOTICE: because of the GreenSock implementation, 
  //all keys need to be case-sensitive as same as the name itself
  //see https://gist.github.com/adriancmiranda/a1f50a27dc98f8e2ce55#file-browserify-shim-json-L44
  TweenLite:'greensock-1.18.5/TweenLite.min',
  CSSPlugin:'greensock-1.18.5/plugins/CSSPlugin.min',
  ScrollToPlugin:'greensock-1.18.5/plugins/ScrollToPlugin.min',
  react:'react-15.1.0/react.min',
  'react-dom':'react-15.1.0/react-dom.min'
},
shim: {
  bootstrap: {
    deps: ['jquery']
  },
  columnize: {
    deps: ['jquery']
  },
  typed: {
    deps: ['jquery']
  }
}
```

Do you have any ideas? Thanks.

**Comment by jackdoyle** [comment]
Hm, I tested with RequireJS and 1.18.5 seemed to work perfectly. I did have to update to the latest version of RequireJS, though. Are you using that? Disclaimer: I'm not an expert with RequireJS at all. Perhaps someone else can chime in who has a solid understanding of the potential issues at play here?

I'm also curious if it'd help in your scenario to add a "../TweenLite" path in addition to "TweenLite".

**Comment by ibio** [comment]
Thanks for quick responding. I downloaded the latest RequireJS(http://requirejs.org/docs/release/2.2.0/minified/require.js) and tested again. The error still exists. 
`require.js:34 GET http://example.com/ibio/master/script/TweenLite.js?bust=20160510 g.load @ require.js:34load @ require.js:29load @ require.js:17fetch @ require.js:17check @ require.js:17enable @ require.js:23enable @ require.js:27(anonymous function) @ require.js:22(anonymous function) @ require.js:7y @ require.js:6enable @ require.js:21init @ require.js:16I @ require.js:13completeLoad @ require.js:28onScriptLoad @ require.js:29
require.js:7 Uncaught Error: Script error for "../TweenLite", needed by: CSSPlugin
http://requirejs.org/docs/errors.html#scripterror`

Would you please paste the code you used RequireJS? Thanks.

**Comment by spalax** [comment]
This error appeared when in CSSPlugin.js appeared 
```
if (typeof(define) === "function" && define.amd) { //AMD
		define(["../TweenLite"], getGlobal);
.....
```
So, is it really required to do a relative path when using AMD ?

**Comment by ibio** [comment]
Exactly!

**Comment by jackdoyle** [comment]
Let me look into that a bit - the tricky thing here is that it's not just for RequirJS, as Webpack seems to default to using that implementation as well and Webpack was playing nicely with the relative path. With all these build systems it can be a bit frustrating to make them all work cohesively. I don't want to make this change you're requesting and have it work great in RequireJS and then break Webpack :) I'll look into it. In the mean time, if anyone has deep experience with most/all of the AMD-based loaders/compilers and can chime in with suggestions, that'd be swell.

**Comment by lagden** [comment]
@ibio Now you need make a map.

```js
// Example config.js

define('config', function () {
	requirejs.config({
		baseUrl: '/js/lib',
		paths: {
			TimelineLite: './gsap/src/uncompressed/TimelineLite',
			TweenLite: './gsap/src/uncompressed/TweenLite',
			CSSPlugin: './gsap/src/uncompressed/plugins/CSSPlugin'
		},
		map: {
			CSSPlugin: {
				'../TweenLite': 'TweenLite'
			}
		}
	});
});
```

**Comment by ibio** [comment]
Thanks @lagden !It seems a really exciting solution. I found this:

> map: For the given module prefix, instead of loading the module with the given ID, substitute a different module ID.

> There is also support for a "*" map value which means "for all modules loaded, use this map config".

http://requirejs.org/docs/api.html#config-shim

I will definitely experiment this and let you guys know the result.

**Comment by jackdoyle** [comment]
1.19.0 should work better for you. Let me know if you run into any other problems.
