### ISSUE TITLE
CSSPlugin will try to require TweenLite in node-like environments

### ISSUE THREAD

**Issue by zlepper** [greensock/GreenSock-JS#153]
I have an app i'm building in Electron. Electron exposes the require methods to the frontend.

CSSPlugin however will try to load TweenLite.js with a require command even if run on the frontend thread. And because it's part of a minified file this will fail with:
`Uncaught Error: Cannot find module '../TweenLite.js'`

I'm not even sure if this can be fixed, and it doesn't prevent functionality, it's just an eyesore in the console.

**Comment by lagden** [comment]
I did an explanation for AMD Modules, maybe this solution works to you too!
https://github.com/greensock/GreenSock-JS/issues/152#issuecomment-225374166

**Comment by jackdoyle** [comment]
Please make sure you're using 1.19.0 or later.
