### ISSUE TITLE
Draggable 1.18.5 update() doesn't work in onDragStart

### ISSUE THREAD

**Issue by tombigel** [greensock/GreenSock-JS#154]
Here is the same test case, one with GSAP + Draggable 1.18.4 and one with 1.18.5.
They contain a draggable with a simple onDragStart function that updates the x and y of the dragged element.

in 1.18.4 it works and in 1.18.5 it doesn't.

1.18.4: http://codepen.io/tombigel/pen/XKderr
1.18.5: http://codepen.io/tombigel/pen/jrqGPX

**Comment by jackdoyle** [comment]
Thanks for posting a perfect reduced test case. Super helpful. We'll look into this soon and get back to you. Please stand by...

**Comment by jackdoyle** [comment]
Here's a preview of the next Draggable release which should resolve this: https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/Draggable-latest-beta.js

Does that work well for you?

**Comment by tombigel** [comment]
looks like it works, but only tomorrow at work I could say for sure
http://codepen.io/tombigel/pen/dXMEjz

**Comment by tombigel** [comment]
Works in our original scenario too. thanks.

**Comment by jackdoyle** [comment]
Fixed in GSAP 1.19.0
