### ISSUE TITLE
npm importing problem with plugins

### ISSUE THREAD

**Issue by batm4n** [greensock/GreenSock-JS#157]
`import 'gsap';` successfully imports TweenMax, but when i want any of the plugins or utilities, I'm lost..

`import Draggable from '../node_modules/gsap/src/minified/utils/Draggable.min.js';`

throws an error:
`Error: Cannot find module '../TweenLite.js'`

**Comment by apertureless** [comment]
Hey @batm4n . Yeah sadly GreenSock is not really es6 import compatible.

It actually would be great if you could do something like

```javascript
import { TweenLite, Draggable } from 'gsap' 
```

However this is not really possible. Don't know about your setup but if you're using browserify, you should try browserify shim.

There you can add the individual paths of the plugins and register them.

After installing browserify-shim just add

```javascript

"browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "TweenLite": "./node_modules/gsap/src//uncompressed/TweenLite.js",
    "Draggable": "./node_modules/gsap/src//uncompressed/utils/Draggable.js",
  },
  "browserify-shim": {
    "TweenLite": "TweenLite",
    "Draggable": "Draggable"
  }
```

**Comment by batm4n** [comment]
works when i replace TweenMax with the 1.18.6 beta in npm_modules
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

**Comment by jackdoyle** [comment]
The AMD require statements just look for "TweenLite" now, not "../TweenLite" so that should help. And you should be able to do a regular ES6-style import for any of the classes that are in TweenMax (like all the eases, TweenLite, TimelineLite, TimelineMax, CSSPlugin, etc.). Please make sure you're using 1.19.0 or later.

**Comment by jackdoyle** [comment]
Oh, and by the way, you may need to add some aliases to your config file. In webpack, it'd look kinda like: 
```javascript
resolve: {
  root: path.resolve(__dirname),
  extensions: ['', '.js'],
  alias: {
    "TweenLite": "src/libs/gsap/TweenLite",
    "CSSPlugin": "src/libs/gsap/plugins/CSSPlugin"
  }
}
```

**Comment by bfred-it** [comment]
> The AMD require statements just look for "TweenLite" now, not "../TweenLite" so that should help. 

I believe this issue is the same as #180 and the solution was to use "../TweenLite.min" instead of "TweenLite", which causes #186
