### ISSUE TITLE
Number with dots replaced by comma

### ISSUE THREAD

**Issue by gabrielstuff** [greensock/GreenSock-JS#158]
Hi !
I'm really happy to be able to use tweenmax for animation. I've noticed one issue, that is kind of hard to reproduce. 
Using chrome and a simple command like : 

`tl.to(parentClass + ' .card-2', cardAnimInDuration, { scale: 1, left: 0, top: 0, rotation: -5, ease: Expo.easeOut, delay: delayDuration }, 'cardsIn')` 

produce a nice animation which render perfectly in chrome.

In chromium it is also perfect.

But in some version of Electron, the content is not visible due to an error in the matrix transform. 

The produced matrix transform is as follow : 

chrome 51.0.2704 : `transform: matrix(0.99619, -0.08715, 0.08715, 0.99619, 56.9881, -22.7032);`
canay chromium : `transform: matrix(0.99619, -0.08715, 0.08715, 0.99619, 56.9881, -22.7032);`
electron 1.2.3 : `transform: matrix(0,99619, 0,08715, 0,99619, 0,08715, 0, 871557);`

You'll notice that the "." dots are replaced by commas... and this breaks the transform property.

I'll be happy to get some help on this issue.

Thanks !

**Comment by jackdoyle** [comment]
@gabrielstuff that's very odd and it certainly sounds like an issue with Electron, not GSAP. Feel free to look at the code that generates the matrix values and you'll see that it's relatively straightforward and there's nothing in there that could possibly be swapping out commas for periods (unless I'm totally missing something). Frankly, I never even heard of Electron until today :) But yeah, I'm pretty confident this is an issue on their end, not with GSAP. Have you contacted the Electron folks about this at all?
