### ISSUE TITLE
npm install gasp

### ISSUE THREAD

**Issue by napcat** [greensock/GreenSock-JS#160]
When I try to install greensock using "npm install gasp" it install a version 0.0.2.

Shouldn't be the latest version 1.18.5?

**Comment by jackdoyle** [comment]
Hm, where exactly are you seeing that 0.0.2 version number? It looks correct (1.18.5) at https://www.npmjs.com/package/gsap as well as in the package.json file.

**Comment by jackfuchs** [comment]
GSAP !== GASP

Sent from my stupid iPhone.

**Comment by jackdoyle** [comment]
Ha, good catch @jackfuchs. Indeed.
