### ISSUE TITLE
Undefined TweenMax/TweenLite/etc if installed via NPM ( v1.18.5 )

### ISSUE THREAD

**Issue by spalum** [greensock/GreenSock-JS#161]
TweenMax/TweenLite ( as well as others ) are undefined if using the source installed via NPM. Note, that these are being included directly via `<script>` and not using modules ( ES6 or other ). Both uncompressed and minified seem to be problematic. However, the source loaded via CDN and direct download all work for the same version number ( v1.18.5 ).

**Comment by jackdoyle** [comment]
Hm, I wonder if it's some strange issue on your end. There is absolutely no difference in the files on the CDN vs what gets installed via NPM, and many thousands of people have been using GSAP via NPM (myself included) and nobody has reported any issues so I'm kinda scratching my head to figure out what might be happening for you. Are you 100% sure you're loading the files properly? (Not that there's anything special you have to do). If you're still having trouble, can you walk me through exactly how I can reproduce the issue?

**Comment by spalum** [comment]
@jackdoyle you may be right in that it's on my end. I'm currently working around it, but thought I should log the issue in case any others were seeing it. I'll try a few more things tonight and let you know if I resolve it. But, to your point if they're the same source and nobody else seeing it—it's likely on my end. Thanks for the quick reply.
