### ISSUE TITLE
Import TweenLite from npm gsap

### ISSUE THREAD

**Issue by willdady** [greensock/GreenSock-JS#164]
I can't figure out how to import TweenLite when using the npm installed version of gsap with Webpack. I get that the default import from gsap is TweenMax but ideally I would like to do the following:

`import { TweenLite } from 'gsap';`

However that doesn't work. Weirdly this works:

`import { TimelineLite } from 'gsap';`

All I'm wanting to achieve is to set `TweenLite.defaultOverwrite`. I'm otherwise only needing `TimelineLite`. I'm using 1.18.5.

**Comment by jackdoyle** [comment]
I bet if you upgrade to 1.19.0 (released yesterday), you'll be fine ;)

**Comment by willdady** [comment]
Ha! Confirmed `import { TweenLite } from 'gsap';` now working. Thanks @jackdoyle :)
