### ISSUE TITLE
onComplete fires on start immediately if repeatDelay = 0

### ISSUE THREAD

**Issue by webloft** [greensock/GreenSock-JS#172]
For example, console.log() is immediately executed if repeatDelay was set to 0. A value > 0 works fine. Omitted property has the same error.
```
new TimelineMax({
  repeat: 3,
  repeatDelay: 0,
  onComplete: function() {
    console.log('completed');
   }
});
```
gsap 1.19.0

**Comment by jackdoyle** [comment]
That sounds like expected behavior if you don't populate the timeline with anything. Remember, animations begin playing immediately, so if you create a TimelineMax instance and then don't add any animations to it, that means it'll have a duration of 0 and its playhead will reach its end and fire its onComplete on the next "tick".

**Comment by webloft** [comment]
I have 23 Tweens in it.

**Comment by jackdoyle** [comment]
Hm. Would you please provide a codepen or jsfiddle example? It's really difficult to troubleshoot blind, but a demo would be super helpful.

**Comment by webloft** [comment]
There is no magic in there. I start with TimelineMax, add some tweens with .from() and .to() and finally call .play() - simple code like that:

```
tl.from(elements.sc1_img1, 0.75, { opacity: 0, left: -100 }, "-=0.75");
tl.from(elements.sc1_text2, 0.25, { opacity: 0, top: -100 });
...
tl.play();
```

- option repeatDelay: 0 / omitted leads to onComplete() immediately after .play()
- option repeatDelay: 0.1 works fine, executes the timeline and finally calls onComplete()

It's maybe a problem with the jQuery-plugin I also using.

my Sources are:
http://cdnjs.cloudflare.com/ajax/libs/gsap/1.19.0/TweenMax.min.js
http://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js
http://cdnjs.cloudflare.com/ajax/libs/gsap/1.19.0/jquery.gsap.min.js

**Comment by jackdoyle** [comment]
Seems to work perfectly: 
http://codepen.io/anon/pen/QKWJEL?editors=0010

What am I missing? Again, it'd be super duper amazingly helpful if you could create a reduced test case that demonstrates the issue. It's just *really* tough to troubleshoot blind.

**Comment by webloft** [comment]
Thank you. I was not aware that the constructor was in global scope but the timeline was just filled after DOM-ready, so your first answer matches perfectly.
