### ISSUE TITLE
ES6 doesn't have {TimelineMax}

### ISSUE THREAD

**Issue by cameronroe** [greensock/GreenSock-JS#174]
`import {TimelineMax} from 'gsap'`

--> `undefined`

?

**Comment by jackdoyle** [comment]
Seems to work fine for me. Very tough to troubleshoot blind, though. Got more details?

**Comment by cameronroe** [comment]
Looks like I was using the bower package which didn't work. The npm module is working correctly. Thanks.

**Comment by jackdoyle** [comment]
Thanks for letting us know.

**Comment by jide** [comment]
Hmmm I have the same issue. I have the feeling that I hit this issue everytime I try to use GSAP npm package.

Can't you just make a regular es6 export ? An index file exporting all modules ?

I do not see how this can work with a main entry in package.json like this ?
```
"main": "./src/uncompressed/TweenMax.js",
```

**Comment by jide** [comment]
Okay I found this issue https://github.com/greensock/GreenSock-JS/issues/114
