### ISSUE TITLE
IndexOutOfBounds

### ISSUE THREAD

**Issue by pergravgaard** [greensock/GreenSock-JS#176]
Take a look at line 2027 in TweenMax.js (version 1.19.0):
a[0] = new Segment(values[0][p], 0, 0, values[(l < -1) ? 0 : 1][p]);

This is a case where l < 0 and l >= -2. Consider the case where l = -1. Then values.length was 1 and:
a[0] = new Segment(values[0][p], 0, 0, values[1][p]);
But the expression values[1] will then be undefined, since values.length was 1.
I guess line 2027 should be:
a[0] = new Segment(values[0][p], 0, 0, values[(l <= -1) ? 0 : 1][p]);

At least that fixed the error in our application.

Best regards, Per

**Comment by jackdoyle** [comment]
Actually, I think it should simply be:
```javascript
a[0] = new Segment(values[0][p], 0, 0, values[0][p]);
```
Agreed? 

Sorry about the problem, and thanks for pointing it out. It's a pretty rare edge case, but I'm glad you ran into it and let us know.

**Comment by pergravgaard** [comment]
Hi again

If l is -2, means the values list is empty which again means values[0] is
undefined. I don't know if the scenario l = -2 ever occurs, but if it does,
we can't read from the values list. I do not know what makes sense as the
fourth argument to the Segment constructor then.

Best Regards, Per

**Comment by jackdoyle** [comment]
Right, I can't imagine how or why someone would ever tween to a completely blank bezier (no values whatsoever). Not even sure how they'd expect BezierPlugin to handle a situation like that (there's literally no data to go from). 

I can't see any scenario where this: 
```javascript
a[0] = new Segment(values[0][p], 0, 0, values[(l <= -1) ? 0 : 1][p]);
```
...would behave any better or differently than this:
```javascript
a[0] = new Segment(values[0][p], 0, 0, values[0][p]);
```
Can you?

**Comment by pergravgaard** [comment]
Hi Jack

No, you're right, the two lines of code will behave the same and none of
them solves the scenario where values is an empty list. But IMHO it would
be nice with a comment or some kind of sanity check of the values list.
Either do the sanity check in the calling method (and just write a comment
about it in this method) or do the sanity check in this method. The Segment
constructor needs a well-defined value as its fourth argument, otherwise we
wouldn't have bumped into this in the first place. When you just look at
the method (as I do now) it's not clear (to me at least) which edge
case/scenario the code is trying to handle. All I can see is that the case
l = -2 won't succeed. But if the case l = -2 ever occurs (or can occur), I
really don't know. I guess you do?

Best regards, Per

**Comment by jackdoyle** [comment]
When you say "sanity check", do you just mean sensing if there are literally no values that the user passed in, and in that case throwing an error or console.log()? Or do you just mean literally writing a code comment that says we expect users to pass at least 1 value in to bezier tweens?

**Comment by pergravgaard** [comment]
Maybe both or maybe only one of them. It depends on the case in question
and what the code is supposed to solve. Sanity checks can be
performancewise expensive, on the other hand they can also avoid doing
heavy computation in a scenario where you can't resolve everything after
all. I'm just saying that if I wrote some code, it would be nice for fellow
programmers (and my self later on) to know what the code was trying to
solve.
The function _parseAnchors in question may be called a lot of times in
which case it may not be a good idea to place a sanity check inside it.
Maybe it makes better sense to do it way before. To me it is a bit
confusing though, that half way through the function body a variable l is
introduced for trying to remedy cases where values.length is either 0 or 1.
If it is 0, we can't remedy it anyway and what we did in the first half of
the function body was a waste.
But if a sanity check has been performed before calling _parseAnchors (we
know values.length >= 1), then the code could still make sense, but in this
case a comment would have been nice.
I guess that's all I'm saying.
Makes sense?

:-) Per
