### ISSUE TITLE
possible time leack

### ISSUE THREAD

**Issue by lucap86** [greensock/GreenSock-JS#178]
Is this a bug? 

*Not paused*
```
z = new TimelineLite({paused:true, onComplete: function(){console.log("Z completed");}});
z.clear()
k = new TimelineLite();
k.clear()
k.call(function(){debugger;z.pause(null, false);});
k.call(function(){debugger;console.log("foo");}, null, window, "+=0.001");
z.add(k);
z.play();
```

*Not paused*
```
z = new TimelineLite({paused:true, onComplete: function(){console.log("Z completed");}});
z.clear()
k = new TimelineLite();
k.clear()
k.call(function(){debugger;z.pause(null, false);});
k.call(function(){debugger;console.log("foo");}, null, window, "+=0.01");
z.add(k);
z.play();
```

*Paused*
```
z = new TimelineLite({paused:true, onComplete: function(){console.log("Z completed");}});
z.clear()
k = new TimelineLite();
k.clear()
k.call(function(){debugger;z.pause(null, false);});
k.call(function(){debugger;console.log("foo");}, null, window, "+=0.1");
z.add(k);
z.play();
```

i think that the issue involve computation of renderer's time param
z.time()  on debugger breakpoint is very close to 0 (≈0.0160...) but not 0.

**Comment by jackdoyle** [comment]
As far as I can tell, no, this is not a bug at all. It's expected behavior. Let me explain...

The browser dispatches a requestAnimationFrame event roughly 60 times per second (though it might be more, depending on the CPU load) which translates to 0.016 seconds. Your first 2 examples have the 2nd call() inserted LESS THAN 0.016 seconds into the timeline, thus on the very first tick the playhead will have shot past that point (remember, the start time is on the current tick). Your 3rd one has it at 0.1 seconds, thus when the pause() call() is triggered, the timeline is still active. 

I checked using a delayedCall() after 0.5 seconds and all timelines were indeed paused as they should be. Did I perhaps misunderstand what you were saying?

**Comment by lucap86** [comment]
I had understood that if

call A => t0 < 16ms and A stop the timeline
call B = t1 < 16ms and t1 > t0 than B is not executed because timeline is paused by A.

Otherwise how can i be sure that B will be paused?
In the worst case, if cpu load is very heavy and we have 10/15/20fps, the code below will do the same of the first example in a 60fps scenario.

```
z = new TimelineLite({paused:true, onComplete: function(){console.log("Z completed");}});
z.clear()
k = new TimelineLite();
k.clear()
k.call(function(){debugger;z.pause(null, false);});
k.call(function(){debugger;console.log("foo");}, null, window, "+=0.06");
z.add(k);
z.play();
```

**Comment by jackdoyle** [comment]
I read your post about 4 times and I'm still a little fuzzy on what the problem is. If you need to pause a timeline at a particular point, it's best to use the addPause() method because that ensures that the playhead doesn't go beyond that spot. Does that help at all?

**Comment by lucap86** [comment]
I cant use addPause because it will add pause at the end of the timeline.
Note that i'm trying to pause z (the parent) inside a k (the child) .call.

The goal is to pause parent timeline inside a child timeline call.

```
k.call(function(){z.pause(null, false); // <---- Here I want to pause everything defined after});
k.call(function(){console.log("This call should be paused by prev k.call");}, null, window, "+=0.01");
```

According to your explanation (on a 60fps scenario):
```
Your first 2 examples have the 2nd call() inserted LESS THAN 0.016 seconds into the timeline, thus on the very first tick the playhead will have shot past that point (remember, the start time is on the current tick). Your 3rd one has it at 0.1 seconds, thus when the pause() call() is triggered, the timeline is still active.
```

the 2nd call is played because it is at t < 16 ms (RAF tick on 60fps scenario).

But if we have an heavy CPU load, for example 15fps scenario, we have a RAF tick every 60ms.
In this case, according to your explanation, if I want to stop the 2nd call I have to put it at t > 60ms.

```
k.call(function(){z.pause(null, false); // <---- Here I want to pause everything defined after});
k.call(function(){console.log("This call should be paused by prev k.call");}, null, window, "+=0.61");
```

This is not deterministic. Since the 1st k.call, that pause the z parent timeline, come first the 2nd k.call should always be paused.

**Comment by jackdoyle** [comment]
Have you tried defining a time for your pause? Like:
```javascript
k.call(function(){z.pause(this.startTime());
```

**Comment by lucap86** [comment]
yes that work and stop parent at child startTime.
but more in general:

```
k.call(function(){
    ... some code;
    z.pause(this.time());
    ... some code;
});
```
will pause parent at the current playhead position.

The question is:
Should the runtime do this automatically when I call pause without "atTime" parameter?

documentation says:

atTime : *
(default = null) — The time (or label for TimelineLite/TimelineMax instances) that the instance should jump to before pausing (if none is defined, it will pause wherever the playhead is currently located).

**Comment by jackdoyle** [comment]
Yes, calling pause() stops the playhead at its current position.
