### ISSUE TITLE
jquery member breaks

### ISSUE THREAD

**Issue by staff0rd** [greensock/GreenSock-JS#179]
[This line](https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L6761) means that if your object has a property or method named `jquery` on it, TweenMax will erroneously run [this code](https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L6767-L6792) (and in my case crash Chrome due to an infinite loop).

**Comment by jackdoyle** [comment]
Sorry to hear that. Would you mind providing a reduced test case so that I can see what's causing the entire browser to crash? 

That line is a performance optimization that allows it to skip the more complicated (time-consuming) logic if it's reasonably expected to be a jquery object. If you've got any ideas to improve that line, let me know. I'm curious why you've got a jquery property on your object(s). Not that it's "wrong" or anything - just totally curious.

**Comment by staff0rd** [comment]
The cause is due to the inifinite loop that is enabled by [_slice](https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L21-L27) due to an `undefined !== undefined` comparison  when the non-array object is passed to it.

Something like this should trigger it;

~~~
var myObj = { value: 0, jquery: true }
TweenMax.to(myObj, 1, { value: 100});
~~~

The reason I had a `jquery` method on my object was purely accidental - I was just testing some jquery integration via it.  I just changed the method name to something else to avoid this.

**Comment by staff0rd** [comment]
Regarding improvement, i'm not entirely sure.  How is this `jquery` property expected to be populated on targets prior to this bug being raised?

**Comment by jackdoyle** [comment]
It's a way to quickly identify a jQuery object, like $(".class") would have it. 

Thanks for the additional info. I'll try to think through some options. Frankly, you're the only person who has ever reported this in all the years of GSAP being out there (and it's on over 2.4 million sites now), and you said you only noticed it as a result of an accident in your own code, so I'm not inclined to think it's a critical issue to address (and skip the quick logic in favor of something more CPU-intensive). Feel free to offer a different perspective.

**Comment by staff0rd** [comment]
Kind of a non-event if your millions of users aren't finding it, might as well close it as it's probably enough to just have it reported.  I seem to have a penchant for discovering these types of errors.

**Comment by jackdoyle** [comment]
Ha ha. Actually, I'm grateful for folks like you who have such a penchant for discovering things like this - it helps make us sharper. But yeah, in this case it's probably not worth the performance cost of changing it. But if anyone else runs into this and it causes issues, we'd certainly be willing to reconsider. Thanks again for reporting it.
