### ISSUE TITLE
Power4 is undefined

### ISSUE THREAD

**Issue by corysimmons** [greensock/GreenSock-JS#181]
XO is upset about this.

![image](https://cloud.githubusercontent.com/assets/224636/21084919/37924c3c-bfd8-11e6-9778-4b20e868f945.png)

I'm `import {TweenMax} from 'gsap'`.

Anything I can do to fix this?

**Comment by jackdoyle** [comment]
Should be as simple as importing it :) 
```javascript
import {TweenMax, Power4} from "gsap";
```
Right?

**Comment by corysimmons** [comment]
I couldn't grep for `Power4` in the gsap npm package so I'd assume it isn't exportable. `Power` seems to exist and have numbers appended to it programmatically, but I don't think it's exporting them. Can you confirm?

**Comment by jackdoyle** [comment]
Yep, it should indeed be exporting all the Power eases (and yes, it builds/defines them programmatically).

**Comment by corysimmons** [comment]
Okay thank you. Sorry I didn't check this earlier and bugged you.

**Comment by jackdoyle** [comment]
No problem, cory. Let us know if you run into any other issues. Happy to help.

**Comment by HugoWeslien** [comment]
Importing worked for me.
