### ISSUE TITLE
iOS 10 incorrectly identified as SafariLT6

### ISSUE THREAD

**Issue by bfred-it** [greensock/GreenSock-JS#183]
GSAP expects the browser version to be single-digit, so it's currently pulling `"1"` out of `"10"`

https://github.com/greensock/GreenSock-JS/blob/94c5d3100f78656c3a336ff1080ce22fba63394d/src/uncompressed/plugins/CSSPlugin.js#L83

Also you can lose the `Number()` because `>` casts strings into numbers anyway

**Comment by jackdoyle** [comment]
Good catch, @bfred-it. Here's a preview of 1.19.1 (uncompressed, TweenMax): https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Better?

**Comment by bfred-it** [comment]
Yep, that fixes it!

I had noticed this because GSAP was setting `backface-visibility` in Safari 10:

<img width="501" alt="screen shot 2016-12-27 at 17 09 30" src="https://cloud.githubusercontent.com/assets/1402241/21494795/c932e808-cbc8-11e6-9c62-552c7e4961a3.png">

https://codepen.io/anon/pen/YpoNvM

**Comment by bfred-it** [comment]
**Alarm, alarm!**

My bad. What I said about `>` is wrong:

```js
"2" > "11"
// => true
```

**Comment by jackdoyle** [comment]
Cool. Okay, so the new version is working well for you, right? No other suggestions/problems?

**Comment by bfred-it** [comment]
Yep it works 👍
