### ISSUE TITLE
TypeError: Constructor Animation requires 'new' [Firefox 50.1]

### ISSUE THREAD

**Issue by lisovskyvlad** [greensock/GreenSock-JS#185]
Hallo, thanks for good library.

I found a problem which is only for Firefox.

TypeError: Constructor Animation requires 'new'.

It happens at line 560 of TweenLine.js
https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenLite.js#L560

```
switch (l) {
  case 0: callback.call(scope); break;
  case 1: callback.call(scope, params[0]); break;
  case 2: callback.call(scope, params[0], params[1]); break;
  default: callback.apply(scope, params);
}
```

**Comment by jackdoyle** [comment]
Hm, it sounds like perhaps a problem in your callback. Do you have a reduced test case we could peek at? A codepen or jsfiddle would be perfect.

**Comment by lisovskyvlad** [comment]
Yeah, sorry for this issue, it was my problem. Don`t know why but I named one variable upcase Animation, and may be js thinks that it`s class/function. Thanks!

**Comment by jackdoyle** [comment]
Cool, thanks for letting us know.
