### ISSUE TITLE
chrome can not get initial absolute top value.

### ISSUE THREAD

**Issue by acroidea** [greensock/GreenSock-JS#20]
my chrome version is 31. some other versions also has the same issue.
If one element is absolute, and it's parent's style is not set height property, its top value will be not correct in chrome in computedstyle.
http://codepen.io/acroidea/pen/jLIdh
the button element's computedstyle is related to window height not its parent. tweenlite can not get the right initial absolute from computedstyle.

**Comment by jackdoyle** [comment]
I'm pretty sure this is working as expected. I checked it in several browsers today and I didn't see any jump. Let me know if I'm missing anything.
