### ISSUE TITLE
visibility change issue  with setTimeout

### ISSUE THREAD

**Issue by lucap86** [greensock/GreenSock-JS#213]
i've seen the IOS fix at
https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L6328

i think that also at https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L6378 a ```document.visibilityState !== "hidden"``` check should be done.

```				
if (document.visibilityState !== "hidden" && _tickerActive && _getTime() - _lastUpdate > 2000) {
```

otherwise setTimeout can awake ticker even if the tab is actually hidden and no raf is requested

**Comment by jackdoyle** [comment]
Thanks for pointing that out. I can implement this. 

I'm curious - did you run into a problem that caused you to make this suggestion?

**Comment by lucap86** [comment]
Yep!
In a timeline with some .call of functions that play webaudio.
sometime audio was played on inactiive tabs.

**Comment by jackdoyle** [comment]
Should be resolved now.
