### ISSUE TITLE
Depends on Angular 2.4.10?

### ISSUE THREAD

**Issue by HomeboxJim** [greensock/GreenSock-JS#214]
Hi, 

I have an Angular 2 project with angular version 2.3.1 (that I just scaffolded right now with `ng new`), and I try to install gsap with 

`npm install gsap --save`

But it gives me this error:

<img width="728" alt="cursor_and_cyphercity_ _-bash_ _97x25" src="https://user-images.githubusercontent.com/21176220/26938412-2a54267a-4c42-11e7-86f2-0d5a30114fce.png">

I don't get it. Why is gsap dependent on Angular 2, and why is it dependent on an Angular 2 version that is not even out yet?

**Comment by jackdoyle** [comment]
GSAP has **zero** dependencies. It certainly isn't dependent on Angular. Sounds like maybe something is off in your configuration(?) I'm not entirely sure.

**Comment by bfred-it** [comment]
This is unrelated to gsap, it's just npm complaining.
