### ISSUE TITLE
CSSRulePlugin don not support ::

### ISSUE THREAD

**Issue by robberfree** [greensock/GreenSock-JS#216]
when try to get rule by use ::
like this:
var rule = CSSRulePlugin.getRule(".navbar__nav__li::before");
i will get undefined.
thanks.

**Comment by jackdoyle** [comment]
I think it's just supposed to be one colon, like `".navbar__nav__li:before"`

Does that work for you?

**Comment by robberfree** [comment]
@jackdoyle  this works.
i just think add :: support may be better.

**Comment by jackdoyle** [comment]
Thanks for the suggestion - I can add that to the next release.
