### ISSUE TITLE
Does TweenMax.js include all plugins, utilities, easing and timeline?

### ISSUE THREAD

**Issue by IsaacHub** [greensock/GreenSock-JS#221]
1. Does `TweenMax.js` include all of the files from `utils`,`plugins` and `easing` folders?
2. Where are the utils `SplitText` and `VelocityTracker`? these files are missing from `utils` folder.
3. In the [documentation](https://greensock.com/docs/) there are 20 plugins listed in left side menu, but inside the folder `plugins`, only 14 are listed. Were they merged into one another?
4. Where can I get all the functionalities in a giant single file?

I'd like to concatenate those files myself, but I don't know which plugins/utils/easing are included in or excluded from `TweenMax.js`, I'm confused, could someone guide me?

**Comment by jackdoyle** [comment]
First of all, welcome to GreenSock. Sorry about any confusion. It probably seems like there's a lot to learn, but trust me - once you get up and running, I think you'll _**love**_ animating with GSAP. Now to answer your questions: 

1. There's a list at the top of the TweenMax.js file as well as on the main TweenMax page: https://greensock.com/tweenmax. TweenMax includes TweenLite, TweenMax, TimelineLite, TimelineMax, CSSPlugin, AttrPlugin, RoundPropsPlugin, DirectionalRotationPlugin, BezierPlugin, and EasePack. So no, it does *not* include all plugins. It doesn't contain any utils. It includes all of the eases except CustomEase, CustomWiggle, and CustomBounce. 

2. Some plugins/utilities/eases are only available to Club GreenSock members. SplitText is one of those. VelocityTracker is part of ThrowPropsPlugin which is also a Club GreenSock membership benefit. See https://greensock.com/club/ to learn about the club or to sign up. When you're a member (and logged in), you can download a zip file containing GSAP with the bonus files. Club GreenSock is the funding mechanism that has fueled ongoing development and support. We have two full-time team members plus several freelancers working on the projects. Please see http://greensock.com/why-license/ for why we do things this way. Ultimately we firmly believe it's better for end users like you.

3.  See answer to (2) above ;)

4. If you want ALL of the files (including bonus plugins/utilities/eases), just sign up for the "Shockingly Green" or "Business Green" level and download the zip file from your account dashboard (or any of the "Download GSAP" buttons on the site). That'll contain every file in minified and uncompressed states, as well as an extra folder with just the bonus files for NPM users. 

If you have any other questions or concerns, please swing by the community forums at https://greensock.com/forums/. There are over 70,000 posts there and 50,000 members. It's a very warm and welcoming place with some extremely smart people willing to help. Post your questions or just read through the discussions - it's an excellent way to learn. 

If you haven't already seen it, I'd definitely recommend first going to https://greensock.com/get-started-js/ where there's a video and text that'll get you up and running fast. 

Happy tweening!
