### ISSUE TITLE
REQUEST: Allow changing the 40px offset for autoScroll in Draggable.

### ISSUE THREAD

**Issue by rkkoszewski** [greensock/GreenSock-JS#222]
Hi,

Is there any chance to have custom offsets in the autoScroll feature in Draggable? Right now its a fixed 40px offset. 

In my case I have a page with a toolbar as overlay, and the page has a permanent padding of the size of the toolbar. The user has to drag the element far under the toolbar in order for the autoScrolling to kick in.

Having a parameter like this would be handy:

```
autoScrollOffsetX = 100 
autoScrollOffsetY = 100
```

or 

```
autoScrollOffsetTop = 100
autoScrollOffsetLeft = 100
autoScrollOffsetRight = 100
autoScrollOffsetBottom  = 100
```

I don't know if such a feature would be desired to be included in Draggable or not. I could implement it myself and make a Pull Request. Would be nice to get some input on this from the devs.

**Comment by jackdoyle** [comment]
Sure, how about autoScrollMarginTop|Left|Right|Bottom? I've implemented that in this preview of the upcoming Draggable (uncompressed): https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/Draggable-latest-beta.js

Better?

**Comment by rkkoszewski** [comment]
Nice! Thank you very much! I'll use the autoScrollMarginTop one then. Looking forward to have it in the release version some day. Greetings.
