### ISSUE TITLE
$(...) is null

### ISSUE THREAD

**Issue by cvissie** [greensock/GreenSock-JS#224]
We are getting quite a lot of these errors on our sentry.io logs. It's the most frequent error it would seem.

I've tracked it down to the following bit of minified code in GSAP (TweenMax.js)

```javascript
"matrix(1, 0, 0, 1, 0, 0)"===d,c&&Ca&&((h="none"===$(a).display)
```

which in turn is this bit of code:

```javascript

			_getMatrix = function(e, force2D) {
				var tm = e._gsTransform || new Transform(),
					rnd = 100000,
					style = e.style,
					isDefault, s, m, n, dec, none;
				if (_transformProp) {
					s = _getStyle(e, _transformPropCSS, null, true);
				} else if (e.currentStyle) {
					//for older versions of IE, we need to interpret the filter portion that is in the format: progid:DXImageTransform.Microsoft.Matrix(M11=6.123233995736766e-17, M12=-1, M21=1, M22=6.123233995736766e-17, sizingMethod='auto expand') Notice that we need to swap b and c compared to a normal matrix.
					s = e.currentStyle.filter.match(_ieGetMatrixExp);
					s = (s && s.length === 4) ? [s[0].substr(4), Number(s[2].substr(4)), Number(s[1].substr(4)), s[3].substr(4), (tm.x || 0), (tm.y || 0)].join(",") : "";
				}
				isDefault = (!s || s === "none" || s === "matrix(1, 0, 0, 1, 0, 0)");
				if (_transformProp && ((none = (_getComputedStyle(e).display === "none")) || !e.parentNode)) {
					if (none) { //browsers don't report transforms accurately unless the element is in the DOM and has a display value that's not "none". Firefox and Microsoft browsers have a partial bug where they'll report transforms even if display:none BUT not any percentage-based values like translate(-50%, 8px) will be reported as if it's translate(0, 8px).
```

It seems that getComputedStyle(e) returns null.

It would also seem that it occurs 99% of the time on Firefox 54. 

I also can't even find the source of why this is happening at all. It's part of the render code, that much I do know. But when it happens from our side I have no idea.

**Comment by jackdoyle** [comment]
Hm, is there any way you could provide a reduced test case that we can peek at, like maybe in a codepen or jsfiddle? That'd be SUPER helpful. Nobody has ever reported an issue like this in all the years of GSAP being out, so I'm a bit baffled as to why Firefox would be returning null for a getComputedStyle() on a valid DOM element. It sounds like you might have some sort of unique scenario (hence my request for a reduced test case).

**Comment by cvissie** [comment]
Actually you know what ...

I think we should close this for now. I see now that it hasn't occurred since our latest release - MY APOLOGIES.

I had the following usage for window resize code:

```javascript
    if (window.TweenMax) {
      TweenMax.set(div, {transformOrigin: "0px 0px", scale: scale, force3D: false});
    }
    else {
      style[transformPrefix] = "0px 0px";
      style[scalingPrefix] = "scale(" + scale + ")";
    }
```

And this error always occurred when resizing and always in an iframe. So i removed the TweenMax code and simply went for the simplistic:

```javascript
  var scalingPrefix;
  var transformPrefix;
  if ("webkitTransform" in document.body.style) {
    scalingPrefix = "webkitTransform";
    transformPrefix = "webkitTransformOrigin";
  }
  else if ("mozTransform" in document.body.style) {
    scalingPrefix = "mozTransform";
    transformPrefix = "mozTransformOrigin";
  }
  else if ("transform" in document.body.style) {
    scalingPrefix = "transform";
    transformPrefix = "transformOrigin";
  }
  else if ("msTransform" in document.body.style) {
    scalingPrefix = "msTransform";
    scalingPrefix = "msTransformOrigin";
  }
```

Just one thing though... I can confirm it only occurs in Firefox (possibly version 54) and always in an iframe. 

![image](https://user-images.githubusercontent.com/571532/28240420-efcf02ba-6981-11e7-9c43-e77cd3baeb4f.png)

![image](https://user-images.githubusercontent.com/571532/28240422-fb9badbe-6981-11e7-97cc-acc1ac0f841f.png)

Just googling this "firefox 54 iframe getComputedStyle" gives a litany of occurrences inside iframes. So I think it definitely was at one point a bug, and has probably since been resolved. Someone at firefox HQ probably reintroduced it with version 54 😉 

https://bugzilla.mozilla.org/show_bug.cgi?id=548397

**Comment by jackdoyle** [comment]
Thanks for the extra info, @cvissie
