### ISSUE TITLE
A Chrome bug when animating SVGs with "non-scaling-stroke"

### ISSUE THREAD

**Issue by tombigel** [greensock/GreenSock-JS#225]
I found a bug in Chrome when trying to animate SVGs that have the "vector-effect: non-scaling-stroke;" attribute on with animations in 3D context.

The browser fails to calculate the stroke and with complex paths (as in my link) it hangs the browser tab.

It's more of an FYI since it's a browser bug, but maybe you could find a way around it with your knowledge of SVGs + JS Animation.

Codepen Demo (Fails on Chrome, Passes on Safari):
https://codepen.io/tombigel/pen/dzbEMJ

**Comment by tombigel** [comment]
Reported to Chromium (If you can make this report better please do, it's the first time I open a bug there)
https://bugs.chromium.org/p/chromium/issues/detail?id=747708&can=2&q=non-scaling-stroke

**Comment by jackdoyle** [comment]
Yeah, that's definitely a browser bug. Good catch - I've never seen that one before. It's unfortunate. Hopefully they'll patch it soon, but in the mean time I think you can rectify (or at least reduce) the problem by simultaneously animating something like strokeMiterlimit or strokeWidth by a tiny (imperceptible) amount, just to trigger repaints.

**Comment by tombigel** [comment]
Thanks

If you follow the bug i opened in Chromium they started an interesting discussion about the causes for the bug, it's a new bug introduced in a minor Chrome 58 update
