### ISSUE TITLE
SplitText throws error when text starts with <br>

### ISSUE THREAD

**Issue by mityok** [greensock/GreenSock-JS#230]
When text starts with <br> (could have empty spaces or &amp;nbsp; before hand) and text is split by lines, error is thrown:

Uncaught TypeError: Cannot read property 'push' of undefined

[codepen](https://codepen.io/mityok/pen/MvGOep)

**Comment by jackdoyle** [comment]
Interesting. Yes, I see what you mean. I never even anticipated that someone would start with a <br>. I just updated the special version of SplitText that's on codepen: https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/SplitText.min.js - does that work better for you? Once you confirm, I can add it to the "official" members-only zip download (the one that's not limited to Codepen). 

Thanks for letting us know about this. Sorry about any inconvenience.

**Comment by mityok** [comment]
thank you for a fast response and for the fix, it resolved the issue.
