### ISSUE TITLE
_doc is undefined in TweenMax.js

### ISSUE THREAD

**Issue by AdamDenoon** [greensock/GreenSock-JS#236]
Hello,

I am using `"gsap": "^1.19.1"` as an npm module in my NativeScript 3.2.0 application. It crashes on Android only, and I get the following error and stacktrace:

```
com.tns.NativeScriptException: 
Calling js method run failed
TypeError: Cannot read property 'visibilityState' of undefined
File: "file:///data/data/org.myorg.myapp/files/app/tns_modules/gsap/TweenMax.js, line: 6436, column: 64
StackTrace: 
	Frame: function:'_checkTimeout', file:'file:///data/data/org.myorg.myapp/files/app/tns_modules/gsap/TweenMax.js', line: 6436, column: 65
	Frame: function:'invoke', file:'file:///data/data/org.myorg.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/org.myorg.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
	at com.tns.Runtime.callJSMethod(Runtime.java:953)
	at com.tns.Runtime.callJSMethod(Runtime.java:937)
	at com.tns.Runtime.callJSMethod(Runtime.java:929)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5455)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
```

The only use of visibilityState in TweenMax.js is for the "_doc" variable, which is assigned the following value:

`_doc = _gsScope.document || {createElement: function() {return _dummyElement;}},`

This value is ultimately undefined. Any help?

**Comment by jackdoyle** [comment]
Hm, it sounds like window.document is undefined in your environment which is problematic. Do you know why there's no window.document? I could provide a workaround that'd avoid that particular error, but it's still rather important for other aspects of GSAP that a document be defined. See what I mean?

**Comment by AdamDenoon** [comment]
I'm not sure at all. As I mentioned, I'm using NativeScript 3.0, and the app does not crash on iOS, and does not crash on the Android when I'm emulating the Android system. It wasn't until I compiled and published the app in the Google Play store (private alpha release) that I received this error from a remote client. I'm not sure how the NPM module is regularly assigning a value to window.document. Do you know how the NPM module does this in the NativeScript environment?

**Comment by jackdoyle** [comment]
Sorry, I'm not sure. Wish I had an answer for you. Never used NativeScript.

**Comment by adamcoulombe** [comment]
@jackdoyle I am occasionally getting a similar issue when using TimelineMax in a node.js environment. 
![image](https://user-images.githubusercontent.com/469038/34999145-022f1512-faaf-11e7-9c88-e1e0e4e7e3c5.png) 

seems to run fine untill the cpu gets under load (maybe some frames are being skipped), and wants do check for a `visibilityState` on a `_doc` that is `undefined`

**Comment by jackdoyle** [comment]
Ah, I think that may be a node-specific thing that's resolved in the next release which can be previewed (uncompressed) at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js - is that better?

**Comment by jackdoyle** [comment]
Should be resolved now.
