### ISSUE TITLE
TweenMax.staggerTo doesn't work on new Chrome

### ISSUE THREAD

**Issue by sxcooler** [greensock/GreenSock-JS#247]
![image](https://user-images.githubusercontent.com/3192045/33717394-c8ee6624-db94-11e7-9fab-09347c8d8d01.png)
These are some code in TweenMax.staggerTo function, in new Chrome like 62.0.3202.94, when typeof(targets) === string
targets become to a dom element instead of an array of dom element, so that it's length is undefined, and l becomes NaN.
and the for loop do nothing at last.

**Comment by sxcooler** [comment]
btw, my selector is ".someClassName", and accidentally there is only one element match the selector.

**Comment by jackdoyle** [comment]
Hm, I can't seem to reproduce this. Works perfectly for me. Do you have a codepen demo we can peek at? A reduced test case would be super helpful.

**Comment by LuQano** [comment]
> Hm, I can't seem to reproduce this. Works perfectly for me. Do you have a codepen demo we 
> can peek at? A reduced test case would be super helpful.

It seems that the issue is reproducible only when using chrome on Mac

**Comment by jackdoyle** [comment]
That's my primary browser (Chrome on a Mac). Can anyone produce a reduce test case that demonstrates the issue? It's really tough to troubleshoot blind. Maybe a codepen? jsfiddle?

**Comment by sxcooler** [comment]
Sorry for the delay, it’s been a very busy time since I start this issue.
I shall make a codepen tomorrow morning. (Chinese time zone)

发自我的 iPhone
