### ISSUE TITLE
Reusing portion of codes in MIT licensed project

### ISSUE THREAD

**Issue by Trung0246** [greensock/GreenSock-JS#249]
Is it possible or will it have conflict with GreenSock Standard License ?

If so do I allowed to copy and paste TLDR; version of Standard License instead copy long version of license? (I can link to long license in the project if you guys want)

If I'm not allowed to copy then can I rewrite that part of code but same feature and still have no conflict with Standard License ?

I can't find the answer while Googling :(

**Comment by Trung0246** [comment]
So... Does this means using whole GreenSock js file is allowed but copy portion of code and paste it does not? Am I allowed to write code that have similar features to GreenSock code? I'm still didn't understand this part as you didn't state clearly

**Comment by jackdoyle** [comment]
Correct - it would **not** be okay to copy portions of GSAP into your own MIT-licensed files. It is copyrighted code. Is there some particular reason you don't want to use GSAP as-is in your project? I definitely want to empower you to accomplish your goals in your project with GSAP as much as possible; it kinda sounds like you're looking for ways to make [at least portions of] GSAP open source and circumvent the license, though, which we believe would ultimately be bad for the ecosystem overall.

**Comment by Trung0246** [comment]
I mean I was planning for re-implementing some functions in GSAP function with same features, as I don't want to include whole large library just for small portion of code.
