### ISSUE TITLE
yoyo not being true? (ScrollMagic)

### ISSUE THREAD

**Issue by jodriscoll** [greensock/GreenSock-JS#252]
Hello!
Fantastic library overall! I've had to learn it over the past 24hrs to replicate some desired behavior from an archaic example website. I've been able to produce most of the functionality at the codepen below, however, I'm running into a challenge with having the behavior `yoyo` a single animation with a `repeat` set to `1`.

**Description**
`yoyo` doesn't appear to be firing. The part of the `to` behavior is to consume 50% of the default scene, with the second half of (the `yoyo` half) completing the other 50% of the scene moving the animated lines back into place.

https://codepen.io/jodriscoll/pen/PRPmem

**Comment by jackdoyle** [comment]
Howdy, @jodriscoll, and welcome aboard the GSAP train ;) It sounds like you're diving in full-force. 

The best place to ask these questions is in our forums at https://greensock.com/forums because there are a lot of smart people there dedicated to helping the community. 

I'm not very familiar with ScrollMagic, so I'm probably not the best person to ask but I noticed one problem for sure: you're passing in your duration values as strings instead of numbers. So instead of '1', use 1 (no quotes). That seemed to fix the behavior (though I may be misunderstanding your goal). 

```javascript
//OLD:
.to( '.line__01', '1', { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" )
//NEW:
.to( '.line__01', 1, { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" )
```

Does that help at all?

**Comment by jackdoyle** [comment]
Also, you could simplify your code a bit since you've got multiple lines going to the same values:

```javascript
//OLD:
  .to( '.line__01', 1, { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" ) // red
  .to( '.line__02', 1, { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" ) // green
  .to( '.line__03', 1, { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" ) // purple
  .to( '.line__04', 1, { x: props.pos, y: props.neg, repeat: 1, yoyo: true }, "together" ) // green
  .to( '.line__05', 1, { x: props.pos, y: props.neg, repeat: 1, yoyo: true }, "together" ) // orange
  .to( '.line__06', 1, { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" ) // red
  .to( '.line__07', 1, { x: props.pos, y: props.neg, repeat: 1, yoyo: true }, "together" ) // purple

//NEW:
  .to( '.line__01, .line__02, .line__03, .line__06', 1, { x: props.neg, y: props.pos, repeat: 1, yoyo: true }, "together" ) // red, green, purple, red
  .to( '.line__04, .line__05, .line__07', 1, { x: props.pos, y: props.neg, repeat: 1, yoyo: true }, "together" ) // green, orange, purple
```

**Comment by jodriscoll** [comment]
@jackdoyle – thanks a ton! That appears to have been the issue!

I'm going to continue refining as I feel we'll need multiple line variations, but this appears to resolve my hiccup I was having – you rock!

I'll sign up on the forums and start posting there, apologies for the post (but thanks for the response!)

**Comment by jackdoyle** [comment]
Excellent, glad things are working well for you now. Enjoy GSAP, and tween responsibly ;)
