### ISSUE TITLE
Wrong backgroundPosition animation when element has more than one background element [Google Chrome]

### ISSUE THREAD

**Issue by Uriziel01** [greensock/GreenSock-JS#255]
Animating backgrondPosition on element that has multiple `background-image` elements on it causes the value to animate from '0 0' over and over again. When performing such animation on element that has only one `background-image` element works as intended.
https://jsfiddle.net/z86vcm03/

EDIT:
I've checked it now and it seems that it works just fine on Firefox and MS Edge. Could this just be a Chrome engine bug?

**Comment by Uriziel01** [comment]
I have also checked reversing the animation engine by using `.set` instead of `.to` in GreenSock and declaring a `transition:all .3s ease` in CSS and that fixes it completely, not an option in my case unfortunately because my animation parameters are adjusted on the fly by the JS code.

**Comment by OSUblake** [comment]
GreenSock does not do the rendering, so when I see a CSS related problem, I always log out the computed style to see the value the browser is using. In Chrome, it reports multiple background positions for container1 and container2. In Firefox and Edge, there is only 1 background position unless you explicitly set it.

https://codepen.io/osublake/pen/dad8a8006f358850ea31388c8a60a39b

**Comment by OSUblake** [comment]
I guess you could split the computed value to see how many background positions the browser expects.

```
"0% 0%".split(",").length; // => 1
"0% 0%, 0% 0%".split(",").length; // => 2
```

**Comment by Uriziel01** [comment]
Fun fact - I ended up just animating `background-position-x` and `background-position-y` separately and that magically resolves the issue ;)
