### ISSUE TITLE
rotateY or rotateX negative values is not working (react)

### ISSUE THREAD

**Issue by hiradarshadi** [greensock/GreenSock-JS#258]
Hi guys. I've been strugling with rotationX and rotationY properties. It accepts the positive numbers and it works very well. However, It doesn't work with the negative numbers, e.g rotationY: -50
I've seen some example which can get me to use jquery, but I don't want to load that.

    "gsap": "^1.20.4"
    "react": "^16.2.0"
    "react-dom": "^16.2.0"

**Comment by jackdoyle** [comment]
Hm, do you have a reduced test case somewhere? It seems to work fine: https://codepen.io/GreenSock/pen/19c1ed489bd762414251b135a241a7b9?editors=0010

Perhaps it's a perspective issue - did you set a perspective on the parent element?

**Comment by hiradarshadi** [comment]
@jackdoyle thanks a lot. It works properly with setting the perspective property.. I suppose perspective was the problem.

**Comment by jackdoyle** [comment]
Excellent, I'm glad that helped. Happy tweening!
