### ISSUE TITLE
Extend GSDevTools

### ISSUE THREAD

**Issue by JeremDsgn** [greensock/GreenSock-JS#263]
Hi!

I'm working around the GSDevTools utility. I would like to create a decorator, for react, to track and debug components with animations.

To make it short, I have a button to enable/disable the gsdevtools. If I enable it, it creates an instance of `GSDevTools.create()`. After this, all I have to do, it's to add a `@GsapTools` decorator to the component with animations I want to debug.

```
@GsapTools
export default class Cube extends PureComponent {...}
```

It's workin-ish, but not really good for the moment. I have multiple questions,

1/ If I don't use any decorators on any components, `GSDevTools.create()` still registered some animations on the dropdown list. Is there a way to init the gsdevtools, without passing any timeline, and doing it afterwards?

2/ My approach would be to have the `GSDevTools.create()` init function on the devtools components file, and then for each components with the decorator, I would use a `GSDevTools.update()` to track the desired animations with the gsdevtools and registered it on the global object.

3/ At the moment, as I said, it's workin-ish. It's works for "autoplay" animations, they will be registered and I will be able to use the dragger, play, pause, loop, everything and it works. As soon as, I use the decorator on a component with an animation that is play after a click for example, it doesn't work anymore. Because the timeline is not defined when the component did mount. Would it be possible to use a `GSDevTools.update()` function to make it debuggable as well?

Thanks,

**Comment by jackdoyle** [comment]
Disclaimer: I'm not at all familiar with React or decorators.

If you want to debug a specific timeline or tween, I'd strongly recommend just passing that to the create() method, like: 
```javascript
GSDevTools.create({animation:yourAnimation, globalSync:false});
```
But if you want it to be in "global" mode, you must keep in mind that by default it only senses any animations that are created within the first 2 seconds of GSDevTools loading but you can extend that further by setting the static globalRecordingTime property like:
```javascript
GSDevTools.globalRecordingTime = 10; //looks for animations created within the first 10 seconds of loading
```
You can also set the selected animation anytime like:
```javascript
yourGSDevToolsInstance.animation(yourAnimation);
```
Does that help at all?

**Comment by JeremDsgn** [comment]
Thanks for your reply, I'll give it a go with your feedbacks!
