### ISSUE TITLE
undefined gsdevtools

### ISSUE THREAD

**Issue by davvyy00** [greensock/GreenSock-JS#264]
<script src="gsap/GSDevTools.js"></script>
The script loads but I get an undefined error when trying to access variable GSDevTools

**Comment by jackdoyle** [comment]
Sorry to hear about the trouble. I'd be happy to help. Can you provide a reduced test case? Maybe a codepen or something? There's a codepen-specific GSDevTools file that you can load at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/GSDevTools.min.js (again, only for on codepen.io). It's just very difficult to troubleshoot blind. I'm curious: where did you get the GSDevTools.min.js file?

**Comment by davvyy00** [comment]
I figured it out, I needed to included other js files, tweenmax and timelinemax, you can close

**Comment by jackdoyle** [comment]
Ah yes, GSDevTools requires TweenMax (or TweenLite, CSSPlugin, and TimelineLite which are all inside TweenMax). Glad you got it working.
