### ISSUE TITLE
1.20.5 breaking changes

### ISSUE THREAD

**Issue by schonert** [greensock/GreenSock-JS#266]
Our entire build is failing due to the ES6 refactor `"export 'Cubic' was not found in 'gsap'`.
Consider putting stuff like this in a major release to prevent breaking builds. 

We're running Tilde Range (`~1.20.3`), as im sure most people are. 

From your [blogpost](https://greensock.com/docs/NPMUsage) i can se the new way of using import would be;
```javascript
// New way
import { Cubic } from 'gsap/TweenMax'

// Old way
import { Cubic } from 'gsap'
```

**Comment by schonert** [comment]
We fixed this by removing the Tilde Range (`1.20.3`)

**Comment by jackdoyle** [comment]
So sorry about that! Yes, Glad you found the "new" way.

**Comment by jackdoyle** [comment]
Oh, also, I'd strongly recommend moving to the "Power" eases which are IDENTICAL to their less intuitively-named cousins: 

- Power1 = Quad
- Power2 = Cubic
- Power3 = Quart
- Power4 = Quint | Strong
