### ISSUE TITLE
gsap 1.20.5 release use es6 modules which has compatibility issues

### ISSUE THREAD

**Issue by maxlk** [greensock/GreenSock-JS#267]
While ES6 modules are supported by all modern browsers, old browsers and old build pipelines doesn't support it.
It's preferred to use **umd** for compatibility.

**Comment by TimvanScherpenzeel** [comment]
Releasing such a major update (including breaking changes) as a patch doesn't make any sense. Pretty reckless behaviour in my opinion. Does GSAP even do semantic versioning?

**Comment by zouloux** [comment]
It took us some time to identify what broken our repo :) It should be version 1.21.0 since the public API has breaking changes.

**Comment by maxlk** [comment]
@zouloux according to semver breaking changes may only be introduced in 2.0.0

**Comment by zouloux** [comment]
@maxlk indeed. Publishing it as a patch only is a bit dangerous.

**Comment by svenvandescheur** [comment]
Yes, these kind of changes should not be done in a minor version as they can fully automatic break builds.

IMO moving forwards is a good thing en should be encouraged. But doing so without breaking existing setups would be highly appreciated.
