### ISSUE TITLE
add .js extensions to imports to allow vanilla loading

### ISSUE THREAD

**Issue by damienmortini** [greensock/GreenSock-JS#270]
Omitting .js extension in imports prevent gsap to be used natively with <script type="module">.
Should't harm to add them ;)

Thanks for the hard work on 2.0!

**Comment by jackdoyle** [comment]
Sure, we should be able to do that in the next release (unless we hear objections before then). Should be fine, though. 

Thanks for the suggestion.

**Comment by jackdoyle** [comment]
Done! 2.0.1 should make you happy.

**Comment by damienmortini** [comment]
Amazing! That was fast 🥇 😃
