### ISSUE TITLE
import 'gsap/ScrollToPlugin'; breaks entire app at latest npm release

### ISSUE THREAD

**Issue by rockmandash** [greensock/GreenSock-JS#274]
```javascript
import 'gsap/ScrollToPlugin';
```
breaks entire app at latest npm release

**Comment by jackdoyle** [comment]
Hm, sorry to hear about the trouble. A few more details would be very helpful. Do you have a reduced test case? Nobody else has reported any such behavior, but I'm eager to explore any potential problems with ScrollToPlugin - can you provide a demo? You're using 2.0.1, right?

**Comment by jackdoyle** [comment]
Well, we're here if you need us. Let us know if you discover what the problem was in your particular setup.

**Comment by rockmandash** [comment]
Thank you!
You are so nice.
I think where the problem is.
If you app is server-side-rendering, then this line will break.
```javascript
import 'gsap/ScrollToPlugin';
```
Here is a minimum Next.js App
package.json
```json
{
  "dependencies": {
    "gsap": "^2.0.1",
    "next": "^6.1.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}

```
/pages/index.js
```javascript
import { TweenMax } from 'gsap';
import 'gsap/ScrollToPlugin'; // this line will break !

export default () => <div>Welcome to next.js!</div>;

```

**Comment by jackdoyle** [comment]
Hm, I'm a bit confused - you're wanting to use ScrollToPlugin in a server-only environment (no browser)? How would that to work? The plugin has code in it that must figure out certain things in the window/document (which probably doesn't exist in your setup, right?)

**Comment by rockmandash** [comment]
You are totally right!
My bad.

**Comment by jackdoyle** [comment]
No worries :) 

Glad it wasn't a bug or something. Have a good night.
