### ISSUE TITLE
Own Ticker

### ISSUE THREAD

**Issue by rtalon83** [greensock/GreenSock-JS#275]
I would like to set my own ticker `requestanimationFrame` in Tweenlite/TweenMax. Is it possible?
Thanks!

**Comment by jackdoyle** [comment]
Are you saying that you want to take control of the internal ticker that drives all of GSAP or are you asking if you can attach a listener to that ticker? The latter is entirely possible:
```javascript
TweenLite.ticker.addEventListener("tick", yourFunction);
```
But if you want to take control of the ticker and update the time/frame values manually, no, that isn't possible.
