### ISSUE TITLE
Can't import in Jest tests.

### ISSUE THREAD

**Issue by Mourdraug** [greensock/GreenSock-JS#277]
I'm working with vue and jest unit tests. I'm checking out how it all works together and I can't run my tests.
When importing TweenLite like so: `import TweenLite from 'gsap/TweenLite'` I get:

```
export const _gsScope = (typeof(window) !== "undefined") ? window : (typeof(module) !== "undefined" && module.exports && typeof(global) !== "undefined") ? global : this || {};
^^^^^^

    SyntaxError: Unexpected token export
```

I'm using `babel-jest` and other ES6 imports seem to work fine. Everything works just fine in development server as well, it only crashes in unit tests.

**Comment by jackdoyle** [comment]
I'm not familiar with Jest, but it sure sounds like whatever you're using doesn't recognize ES6 code like imports/exports. Perhaps it's an order-of-execution thing, like you need to transpile things to ES5 first, then run those tests(?)

**Comment by Mourdraug** [comment]
It might be order-of-execution kind of issue, but it's kinda weird, because import statement itself works (otherwise it'd throw `Unexpected token import` instead), error actually occurs further down the stack trace.
