### ISSUE TITLE
Browserify config being stripped from package.json

### ISSUE THREAD

**Issue by kinglozzer** [greensock/GreenSock-JS#280]
This issue is actually two-fold for me... some background here: https://greensock.com/forums/topic/18681-syntaxerror-import-and-export-may-only-appear-at-the-top-level-220-while-parsing-node_modulesgsaptweenlitejs/

# Issue 1

When I run `npm install gsap`, the `package.json` that’s installed in `node_modules/gsap/package.json` doesn’t contain the Browserify config here: https://github.com/greensock/GreenSock-JS/blob/2.0.2/package.json#L61-L63. It appears to work as intended if I add it manually, is the npm publishing process somehow stripping this or am I misunderstanding how `package.json` files work?

# Issue 2

Just adding `"browserify": { "transform": ["babelify"] }` still results in the following error for me: 

> 'import' and 'export' may appear only with 'sourceType: module'

If I instead add the following, everything compiles as expected:

```json
"browserify": {
  "transform": [["babelify", { "presets": ["@babel/preset-env"] }]]
}
```

---

I hate to open an issue which just says “changing X to Y fixes it for me” without investigating it in more detail, but I have no prior experience with GSAP (and little JavaScript experience in general) so I’m afraid I can’t offer much more insight!

**Comment by jackdoyle** [comment]
I don't mind adding that to the next release (unless someone chimes in here to object). Unfortunately I'm just not terribly familiar with Browserify or what exactly is required to make things behave. Everyone's configurations seem to vary wildly. Hopefully the preset-env will be acceptable to all the Browserify/Babel folks :)

**Comment by jackdoyle** [comment]
Oh, I just had a thought - did you try adding a .babelrc configuration file to your environment? Perhaps that's where you can define your own preset (rather than requiring it to be set in the GSAP package.json). See https://babeljs.io/docs/en/next/babel-preset-env.html

**Comment by kinglozzer** [comment]
Thanks for taking a look at this @jackdoyle

I can work around the issue by using the following transform, similar to what’s described here https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed:

```js
.transform('babelify', {
  global: true,
  ignore: [
    new RegExp('node_modules\/(?!gsap)')
  ],
  presets: ['@babel/preset-env']
})
```

I don’t mind if you’d just rather close this, JavaScript isn’t my forte so I can’t really offer much advice (and it’s obviously not something that gets requested often 😉) I just thought I’d pass on the suggestion that seemed to help for my particular setup

**Comment by jackdoyle** [comment]
Great, thanks @kinglozzer. Enjoy the tools!
