### ISSUE TITLE
Setting passive:false on iOS Safari 9 is not supported and causes issues

### ISSUE THREAD

**Issue by Sembiance** [greensock/GreenSock-JS#282]
In `1.20.5` the usage of `addEventListener` was changed where if `capture` isn't set then `{passive:false}` is used instead of `undefined`.

Passive events are not supported in Safari 9 under iOS and passing an object like this as an argument 
 to `addEventListener` causes Draggable to stop working after dragging/dropping once.

Simple test case: https://codepen.io/Sembiance/pen/oPMBdr

You should be able to drag the card around, let go and then drag it some more, let go, etc.

With iOS Safari 9 the first drag works, but after letting go you can no longer drag the card anymore.

Reverting to version `1.20.4` fixes the problem and `2.0.2` can be fixed by making a simple change.

Support for this property should be checked first before using. This can be done once at top of file:
```
var supportsPassiveOption = false;
try {
	var opts = Object.defineProperty({}, 'passive', {
		get: function() {
			supportsPassiveOption = true;
		}
	});
	window.addEventListener('test', null, opts);
} catch (e) {}
```

Then line 808 in Draggable.js should be changed from:
https://github.com/greensock/GreenSock-JS/blob/53f4a8d186948dc69f315e3a57bc4e41eb764b98/src/uncompressed/utils/Draggable.js#L808
to: `capture = capture || (supportsPassiveOption ? {passive:false} : undefined);`

**Comment by jackdoyle** [comment]
Thanks for tracking that down and providing a solution!

How's this version (uncompressed)?: 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/Draggable-latest-beta.js

Does that work well for you?

**Comment by Sembiance** [comment]
Yes! That version works great!

I confirmed it with a new test case that points at that version: https://codepen.io/Sembiance/pen/PddKJm

I also confirmed that it fixes the problem on my website.

When it gets released into the public release I'll test again to make sure.

Thanks again.
