### ISSUE TITLE
how to use throwProps in Draggable  when use npm import Draggable.

### ISSUE THREAD

**Issue by believeZJP** [greensock/GreenSock-JS#284]
```

import TweenMax from "gsap/TweenMax";
import Draggable from "gsap/Draggable"; 
import { CSSPlugin, ThrowPropsPlugin }  from "gsap/all";
const plugins = [ CSSPlugin, ThrowPropsPlugin ];

Draggable.create($dragMe, {
   type:"x, y",
   throwProps: true, //？？？
   edgeResistance: 
});

```

It's not working like [demo](https://greensock.com/docs/Plugins/ThrowPropsPlugin)

**Comment by jackdoyle** [comment]
No problem. And yes, if you'd like to get ThrowPropsPlugin, just join Club GreenSock: https://greensock.com/club/

Happy tweening (or dragging)!

**Comment by its-rj** [comment]
Is it possible to test that feature (within my own Laravel Project — not Codepen) before buying a license?

**Comment by jackdoyle** [comment]
@its-rj, The only way to try out one of the members-only plugins is on codepen (or jsfiddle) using the special URLs listed at https://codepen.io/GreenSock/full/OPqpRJ/ (which only work on those domains like codepen.io and jsfiddle.com). 

But don't worry - we offer a satisfaction guarantee so if you sign up and don't like something (for any reason), we'll gladly issue a refund. We're passionate about having happy customers around here. 

Happy tweening (or dragging in your case) ;)
