### ISSUE TITLE
Why is there no 'DrawSVGPlugi'?

### ISSUE THREAD

**Issue by 81777268** [greensock/GreenSock-JS#287]
‘DrawSVGPlugi’ installation package not found！

**Comment by jackdoyle** [comment]
DrawSVGPlugin is a membership benefit of Club GreenSock - see https://greensock.com/club/. That's in all the documentation as well, but sorry about any confusion there. Once you sign up, you can download it from the GreenSock site. 

You can try it for free on codepen anytime - see https://codepen.io/GreenSock/full/OPqpRJ/ for the special URLs to all the bonus plugins that come with Club GreenSock membership. To understand why we do it this way, see https://greensock.com/why-license 

Happy tweening!
