### ISSUE TITLE
yoyoEase not working on gsap latest

### ISSUE THREAD

**Issue by sm1215** [greensock/GreenSock-JS#291]
Hey, so it seems yoyoEase is not being correctly applied in the latest version of Greensock TweenMax. I've altered one of the demos for yoyoEase to demonstrate on codepen. ([Demo taken from here](https://greensock.com/yoyoEase))

In codepen, I've switched the source of TweenMax from 1.20.4 to 'latest' in settings and you should be able to see that the regular ease property is also being used for yoyoEase. I'm not sure that this behavior reflects what is described in the documentation, but if I'm mistaken about anything feel free to close / ignore.
https://codepen.io/sm1215/pen/VVJQBz

Thanks!

**Comment by jackdoyle** [comment]
I know this is gonna sound really strange, but the "/latest/" version on the CDN is really old - 1.18.0 to be exact. CloudFlare dropped support for it and refused to update that directory years ago. We begged and pleaded, but they enacted a policy against supporting it (for any library - they weren't singling out GSAP). So your demo is using a version that didn't have yoyoEase yet. Update to the latest version and you'll see that it works great. :)

In short, never use the "/latest/" URL again. 

And looking back, I understand why CloudFlare made the decision - they were trying to protect against sites/apps suddenly breaking if/when a new version was swapped in for that same URL. Like if the newer version introduced a breaking change or a new bug. Makes sense, although it caused a lot of confusion for our users back when they enacted that policy (and apparently it's still causing some confusion). Sorry about that.

**Comment by sm1215** [comment]
Ooh, got it. Thanks for the quick reply! I had no idea
