### ISSUE TITLE
GSAP & Sentry Error - TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by soypaduano** [greensock/GreenSock-JS#293]
```
{snip} rn[e]},_refreshBuffer:function(e){var t=this;return e._node.bufferSource=n.ctx.createBufferSource(),e._node.bufferSource.buffer=r[t._src],e. {snip}
* VERSION: 1.19.1
* DATE: 2017-01-17
* UPDATES AND DOCS AT: http://greensock.com
*
* Includes all of the following: TweenLite, TweenMax, TimelineLite, TimelineMax, EasePack, CSSPlugin, RoundPropsPlugin, BezierPlugin, AttrPl {snip}
```

**Comment by soypaduano** [comment]
This is the user agent where it appeared: 

Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1

**Comment by jackdoyle** [comment]
Hm, can you please provide a reduced test case and also use the latest version of GSAP? I'm not sure what exactly you're saying the problem is or how to reproduce it, but I'd like to help.
