### ISSUE TITLE
Draggable on IOS Safari Mobile working just once

### ISSUE THREAD

**Issue by soypaduano** [greensock/GreenSock-JS#296]
**works on 0.16.2**
**does not works on 0.16.2 onwards**

Hello, 

We use the draggable of GSAP for dragging blocks into a scene: the thing is that it works perfectly the first time, but, the second time we try, it doesn't work and it doesn't show any errors on console. 

Reading about this issue, I found this: https://greensock.com/forums/topic/19415-draggable-works-only-once-on-android-webview/ and this https://stackoverflow.com/questions/53439868/element-drag-working-only-once-on-webview both of them in Android WebView. For me is in IOS. I'm using an IOS 10.3.3. 

Do you know why is this happening? Thank you very much.

**Comment by jackdoyle** [comment]
I find myself in the same position as I expressed in the greensock forums post you linked to - without a clear demo that's reproducible and editable, I'm at a loss. I just tried using Draggable on my iPhone Xs and it worked perfectly. I dragged many times. Is there a codepen demo you could link to or something? I'd love to help.

**Comment by jackdoyle** [comment]
Also, what version are you using right now? And out of curiosity, does this one work better for you? 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/Draggable-latest-beta.js

(that's an uncompressed beta version of the upcoming release).

**Comment by soypaduano** [comment]
I don't know why, but i can't reproduce it anymore... I don't know, maybe was my code. Still, thanks.
