### ISSUE TITLE
CSSPlugin getMatrix when parent element is display='none'

### ISSUE THREAD

**Issue by mityok** [greensock/GreenSock-JS#297]
when having a tween element with css transformations which is hidden (display:'none') inside parent element,  it's not getting calculated. only if the element it self is hidden there is a condition that force it to be displayed.
suggestion add a recursive parent check:
`_isParentHidden = function(el) {
  while (el) {
    var cs = _getComputedStyle(el);
    if (cs.display === 'none') {
      return el
    }
    el = el.parentNode
    if (el === _doc.body) {
      return
    }
  }
  return null
}`
and add it to current logic of hidden element:
`if (_transformProp && ((none = (!_getComputedStyle(e) || _getComputedStyle(e).display === "none")) || !e.parentNode || (isParentHidden = _isParentHidden(e)))) { `
and then just attach that element to DOM
`if(isParentHidden){
  n = isParentHidden.style.display;
  isParentHidden.style.display = "block";
}`
and after get style, remove it:
`if(isParentHidden){
  isParentHidden.style.display = n;
  n=null;
}`

**Comment by jackdoyle** [comment]
Thanks for the suggestion, @mityok. Would you happen to have a reduced test case, perhaps in codepen that we could look at? I'm pretty apprehensive about adding/removing things from the DOM like that and adding all the recursive stuff that could hurt performance, but maybe it'd be worthwhile. I'd prefer to see a practical use case to make sure I fully understand what's at play and verify there are no other workarounds that don't require such trickery.

**Comment by mityok** [comment]
thank you very much for your response, this is the simplest example that illustrates the issue:
https://codepen.io/mityok/pen/JxJrzo

**Comment by jackdoyle** [comment]
Thanks for the demo! It isn't really feasible to fix it for ALL cases (like if there are CSS selectors that will break by adding it to the root), but I think I've got a workaround that'll resolve the vast majority of cases (including yours). You can preview it in this [uncompressed] version of the upcoming release of TweenMax:
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Is that better?

**Comment by mityok** [comment]
looks great, the use of `offsetParent` is exactly what i meant, just wasn't aware of that property, thank you for all your great work!
