### ISSUE TITLE
Bug: Function-based values, called 2 times

### ISSUE THREAD

**Issue by SvyatoslavPozhydaev** [greensock/GreenSock-JS#300]
Codepen: https://codepen.io/anon/pen/ZwqwNx?editors=1111

**Comment by jackdoyle** [comment]
Great catch! That'd only happen on transform-related values and it should be fixed in the next release (due out within the next week). You can preview it (uncompressed TweenMax) here: 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

Better?

**Comment by SvyatoslavPozhydaev** [comment]
Yes,  its better.
