### ISSUE TITLE
Request: QuaternionsPlugin js port

### ISSUE THREAD

**Issue by clabraham2** [greensock/GreenSock-JS#304]
It appears that the QuaternionsPlugin is only for AS2/AS3 at the moment. This would be really handy to have ported to js to tween with slerp.

**Comment by jackdoyle** [comment]
In almost 7 years, I think this is the first (or maybe second) time someone has requested this, so I don't think it's terribly useful for most of the audience, thus it's not a high priority at the moment. We'll certainly keep it in mind for the future though and watch for similar requests. 

In the mean time, you're welcome to use the ActionScript-based plugin as a template and author your own plugin using the TEMPLATE_plugin.js file. 

Happy tweening!
