### ISSUE TITLE
pixi v5 support

### ISSUE THREAD

**Issue by SeasonCCC** [greensock/GreenSock-JS#313]
Does pixi plugin support pixi v5? I try to animate PIXI.Graphics and change the width of PIXI.Graphics.geometry.graphicsData.shape. It doesn't work.

**Comment by OSUblake** [comment]
Yes, the plugin supports v5, but you wouldn't need the plugin to animate a property on PIXI.Graphics.geometry.graphicsData.shape. I don't even know if you can animate shape data like that. Please provide a demo so we can see what you're doing.

**Comment by SeasonCCC** [comment]
This is my code
`      
const loadingFill = new PIXI.Graphics()
      loadingFill.beginFill(0xffffff, 1)
      loadingFill.drawRect(
        this.options.width * 0.15,
        this.options.height * 0.5,
        0, // I want to change this value by using tweenmax
        30
      )
`

**Comment by OSUblake** [comment]
You can animate a proxy object, and then use an onUpdate callback to draw the graphics using properties from the proxy object.

https://codepen.io/osublake/pen/67985b840e12c07cc43c4b6050fa7949

**Comment by SeasonCCC** [comment]
Nice~ Thank you for answering so quickly.
