### ISSUE TITLE
Use Tweenmax from cdn with webpack

### ISSUE THREAD

**Issue by shubhra14** [greensock/GreenSock-JS#314]
Hi,

I'm loading tweenMax from cdnjs however, I'm unable to make this work in my vue webpack setup. I'm getting `TweenMax is not defined`

![Untitled-1](https://user-images.githubusercontent.com/5490862/64491341-4f093e80-d285-11e9-90f3-612f3a89b7cf.jpg)

Loading script
`wp_enqueue_script( 'tweenmax', 'https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js', array(), false, true );`

webpack.dev.config.js
```
module.exports = {
  entry: path.resolve(__dirname, 'src/app.js'),
  mode: 'development',
  devServer: {
    hot: true,
    headers: { 'Access-Control-Allow-Origin': '*' }
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'http://localhost:8080/',
    filename: '[name].app.js',
    chunkFilename: '[name].app.js',
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.js$/,
        loader: "babel-loader",
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader'
        ]
      }
    ]
  },
  plugins: [
    new VueLoaderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new BundleAnalyzerPlugin()
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src')
    },
    extensions: ['*', '.js', '.vue', '.json']
  },
  externals: {
    jquery: 'jQuery',
    TweenMax: 'TweenMax',
  }
}
```

.vue file
```
import TweenMax from 'TweenMax'

$(el).each(function(i){
        TweenMax.from($(this), time, {
          opacity: 0,
          x: 0,
          y: that.random(-200, 200),
          z: that.random(500, 1000),
          // scale: .1,
          delay: i * delay,
          yoyo: true,
          repeat: -1,
          repeatDelay: time * 10,
          ease: Power1.easeOut
        });
      });

```

**Comment by jackdoyle** [comment]
I'm pretty sure this isn't a GSAP-related thing and I'm not a Webpack expert. I wonder if perhaps you meant to do: 
```
import TweenMax from 'gsap'; //not 'TweenMax'
```
? 

Maybe that's not accurate, though, because you're defining TweenMax as an external rather than importing it from the NPM package. In that case maybe you need to just skip the import call? Again, I'm probably not the best person to answer that question because it's more Webpack related. I'd be happy to help with anything GSAP-related though.

**Comment by shubhra14** [comment]
I really appreciate you replying and trying to help. Turns out I was making the silly mistake of loading TweenMax after my main script. Thank you for your time.

**Comment by jackdoyle** [comment]
@shubhra14 no problem! It happens to the best of us. Thanks for letting us know.
