### ISSUE TITLE
TweenLite.delayedCall is not called in WKWebView on locked iPad

### ISSUE THREAD

**Issue by anivaros** [greensock/GreenSock-JS#315]
Hello! Found strange issue:
I have iOS app with WKWebView control. If device is locked, function TweenLite.delayedCall called only after device unlock and app becoming active.
Just setTimeout func works fine.

Can it be fixed and what difference between delayedCall and setTimeout?

Thank you!

**Comment by ZachSaucier** [comment]
Hey anivaros,

Jack can correct me if I'm wrong here, but I believe that GSAP by default only runs when the window has focus. You can disable this functionality by using 

```
 TweenLite.ticker.useRAF(false);
 TweenLite.lagSmoothing(0);
```

For more info, see [this thread](https://greensock.com/forums/topic/11831-solved-tweenlite-animation-stops-when-window-lost-focus/?tab=comments#comment-48365).

**Comment by jackdoyle** [comment]
Yes, @ZachSaucier is exactly right. Browsers throttle down their requestAnimationFrame() calls to about 2fps when the tab is inactive/hidden. They typically do the same thing for setTimeout() calls as well. GSAP automatically applies lagSmoothing to help ensure that you don't have a big jump after a lag, but of course you can disable that if you prefer.
