### ISSUE TITLE
New version of ScrollTrigger doesn't refresh matchMedia

### ISSUE THREAD

**Issue by minimit** [greensock/GreenSock-JS#508]
There's a problem with the method `ScrollTrigger.refresh()` when you use `ScrollTrigger.matchMedia`, only on latest version of gsap. With the version `3.4.2` for example https://cdnjs.com/libraries/gsap/3.4.2 the problem didn't occur.

Here's the demo https://codepen.io/minimit/pen/dyvoXZa
You can see that if you resize the scrolltrigger doesn't refresh.

**Comment by jackdoyle** [comment]
You only see the problem if you purposely **remove** the "resize" autoRefreshEvent, right?

**Comment by jackdoyle** [comment]
Would you please verify that the upcoming release in this fork of your CodePen works well for you?:

https://codepen.io/GreenSock/pen/GRxdyay?editors=0010

**Comment by minimit** [comment]
> Would you please verify that the upcoming release in this fork of your CodePen works well for you?:
> 
> https://codepen.io/GreenSock/pen/GRxdyay?editors=0010

Yes tested also on website and works properly

**Comment by jackdoyle** [comment]
Thanks for verifying. We hope to release the update within the next few weeks.

**Comment by jackdoyle** [comment]
Fixed in latest release.
