### ISSUE TITLE
TweenMax: Failed to execute 'scrollTo' on 'Window'

### ISSUE THREAD

**Issue by binarykitchen** [greensock/GreenSock-JS#57]
I am getting this error in the console:

```
Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': 2 arguments required, but only 0 present. 
```

My code is simple as following:

``` js
$(document).ready(function($) {
    var controller = new ScrollMagic()

    $(document).on("click", "nav a[href^=#]", function (e) {
        var id      = $(this).attr("href"),
            $elem   = $(id)

        if ($elem.length > 0) {
            e.preventDefault()
            TweenMax.to(window, 0.5, {scrollTo: {y: $elem.offset().top}})

            if (window.history && window.history.pushState) {
                history.pushState('', document.title, id)
            }
        }
    });
})
```

and the markup is very simple:

``` html
  ...
  <body>

    <main>
      <section id="intro">
        <h1>This is who we are</h1>
        <h2>The Manifesto</h2>
        <p>Scroll down to play</p>
      </section>
    </main>
    <nav>
      <ol>
        <li><a href="#intro">Intro</a></li>
      </ol>
    </nav>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/vendor/jquery/dist/jquery.min.js"><\/script>')</script>

    <script src="/js/vendor/gsap/src/minified/jquery.gsap.min.js"></script>
    <script src="/js/vendor/gsap/src/minified/TweenMax.min.js"></script>
    <script src="/js/vendor/ScrollMagic/js/jquery.scrollmagic.min.js"></script>

    <script src="/js/main.js" type="text/javascript"></script>
  </body>
  ...
```

Can you explain this?

**Comment by savva-shishak** [comment]
Does anyone know what to do with the error "Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': parameter 1 ('options') is not an object." when i use webpack?

**Comment by jackdoyle** [comment]
@savva-shishak It sounds like you just forgot to load ScrollToPlugin (or perhaps your build system dumped it as part of tree shaking which you should be able to resolve by directly referencing ScrollToPlugin somewhere in your code).

**Comment by savva-shishak** [comment]
I am new to this topic, could you tell me where and how to announce ScrollToPlugin?

**Comment by savva-shishak** [comment]
thank you for noticing

**Comment by jackdoyle** [comment]
> I am new to this topic, could you tell me where and how to announce ScrollToPlugin?

I assume you mean "load", not "announce", right? Sure, you can load ScrollToPlugin from the CDN or download it from greensock.com or github or NPM. Lots of options. Have you read the "getting started" article? https://greensock.com/get-started-js

**Comment by savva-shishak** [comment]
I sometimes am not attentive, thanks for helping me. You have a very cool platform. )

**Comment by jackdoyle** [comment]
No problem at all! Happy to help. If you need anything else, there's a fantastic community at https://greensock.com/forums. It's a great place to learn even if you don't post a question. 

Enjoy!
