### ISSUE TITLE
Support for rotate3d (which is "rotation around custom axis")

### ISSUE THREAD

**Issue by fregante** [greensock/GreenSock-JS#73]
Greensock doesn't support `rotate3d` correctly: http://codepen.io/bfred-it/pen/sHyFg

![rotate3d not supported](https://cloud.githubusercontent.com/assets/1402241/4646785/74411b74-5476-11e4-8b72-da27536f975a.gif)

**Comment by blowsie** [comment]
Old ticket I know, but is there any way this can be achieved without using  `transform: 'rotate3d(...` ?

**Comment by jackdoyle** [comment]
HI @blowsie - can you provide more details please? I'm not sure what exactly you're trying to do. A reduced test case in codepen would be super helpful.
