### ISSUE TITLE
Firefox SVG Animation: Question & NS_ERROR_FAILURE with hidden elements

### ISSUE THREAD

**Issue by benwick** [greensock/GreenSock-JS#78]
Hello,

first of all thanks for your update and the newly implemented cross browser SVG tweenings capabilities. Exactly what I needed! But first of all I have a question: It seems in Firefox tweening of transform related properties is done with the transform attribute of an SVG node. Why? I thought that is only necessary in IE...

But more importantly: If a newly created SVG node or a parent of a newly created SVG node is not displayed (display: "none"), you can't tween that element. Javascript will throw a NS_ERROR_FAILURE exception. As far as I do understand this issue it has to do with a bug reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=612118 ... I don't know, if there is anything you can do about that. But it is a little bit aof a show stopper ;)

**Comment by jackdoyle** [comment]
I believe this is resolved in 1.15.1

**Comment by rasalshri** [comment]
If you are using html template and css, javascript then ,
remove class with property display:none above the map class and add some new class
after loading or executing getbox function attach that removed class(having property display: none) through javascript.
it works for me , and simple and easy thanks.
it is simple and quick solution
