### ISSUE TITLE
Support for transformOrigin "center" (and possibly other keywords)

### ISSUE THREAD

**Issue by bfred-it** [greensock/GreenSock-JS#81]
I noticed that this code worked fine until 1.14

```js
    tl.set('#lid, #eye', {
      transformOrigin: 'center'
    })
```

But since then, it requires `50% 50%` to work the same way. Can you add support for it?

This demo uses 1.13.2: http://codepen.io/bfred-it/pen/pvgPNg

**Comment by jackdoyle** [comment]
Should be fixed in 1.15.1. Thanks.
