### ISSUE TITLE
BezierPlugin: x/y goes NaN when all the bezier values are the same

### ISSUE THREAD

**Issue by azazdeaz** [greensock/GreenSock-JS#82]
Hi!, i've ran into this:
http://codepen.io/azazdeaz/pen/RNGExW?editors=001

When all the values of the bezier have the same x,y property, (so the elem don't move actually) the elem._gsTransform.x/y will change to null (or NaN in an other test). After this, none of the transform related animations will be working.

It's very easy to avoid this issue, but if you're not aware of it, it's can take a long time to figure it out, why did everything stop moving:)

**Comment by jackdoyle** [comment]
This is resolved in the latest version. Thanks for pointing it out.
