### ISSUE TITLE
className + -webkit-

### ISSUE THREAD

**Issue by stephanedemotte** [greensock/GreenSock-JS#85]
Hi,

I have some issue since the last update with "-webkit-"

Not sure this bug has been fixed
- FIXED problem caused by some Webkit browser reporting redundant/duplicate transform values (in both "transform" and "WebkitTransform") of the computed style which could cause className tweens to act oddly.

I make a simple TweenMax.to('element', 1, {className: "+=active"});
and bam !

![screen shot 2015-01-27 at 10 46 47](https://cloud.githubusercontent.com/assets/2158130/5916466/daca12dc-a611-11e4-971c-db4567ed74bc.png)

Any idea ?

*** EDIT

http://codepen.io/stephanedemotte/pen/bNRXYO
I think TweenMax + normalize cause the issue.
Normalize is in bootstrap :/ 

Need some help ;)

*** EDIT 2

Ouppss
Same issue without normalize, but only on Safari and Chrome.

*** EDIT 3
Everything good with gsap : 1.15.0

**Comment by jackdoyle** [comment]
Yep, fixed in 1.15.1

**Comment by jackdoyle** [comment]
No, actually, it will be fixed in 1.15.2. Sorry. I misunderstood the issue. I already have it fixed in my local copy of CSSPlugin and will push it up with the next tag. Let me know if you need it sooner and I can send it to you.

**Comment by stephanedemotte** [comment]
we are on hold with 1.15.0 :)
Thanks a lot !
