### ISSUE TITLE
DrawSVG suggestion

### ISSUE THREAD

**Issue by artemist** [greensock/GreenSock-JS#86]
Is there a way (or is there a parameter you can pass that I'm not aware of) that would allow for DrawSVG to have different ways to draw the stroke? 

As you see on https://maxwellito.github.io/vivus/ there are 3 different ways to draw the stroke, the first and third seem possible with a staggerTo/From with individual classes on each stroke. The async seems a little harder to accomplish but would be cool to include if possible.

As always, thanks for all of your hard work guys.

**Comment by jackdoyle** [comment]
Absolutely - it should be as simple as one line of code. Here's a demo:
http://codepen.io/GreenSock/pen/937f2f7572f3439ba1cc5701c38b62fd

**Comment by artemist** [comment]
oh perfect! you guys are so on it, as usual. Thanks!
