### ISSUE TITLE
No tags found in git://github.com/greensock/GreenSock-JS.git

### ISSUE THREAD

**Issue by tom10271** [greensock/GreenSock-JS#92]
in my scripts folder I run: bower install gsap --save

I have no idea why I cannot install it with bower.

What can I do for solving it?

**Comment by tom10271** [comment]
D:\AppServ\www\DO\scripts>bower install gsap --save
bower gsap#*                not-cached git://github.com/greensock/GreenSock-JS.git#*
bower gsap#*                   resolve git://github.com/greensock/GreenSock-JS.git#*
bower gsap#*              ENORESTARGET Tag/branch master does not exist

Additional error details:
No tags found in git://github.com/greensock/GreenSock-JS.git
No branches found in git://github.com/greensock/GreenSock-JS.git

**Comment by JonDum** [comment]
My hunch is that this is a configuration problem. Can you clone that same repo from the command line using `git clone`? Windows is a bitch and a half to get working right.

**Comment by jackdoyle** [comment]
Yeah, it sounds like a configuration problem. There are definitely tags in the git repo.
