### ISSUE TITLE
Timeline eventCallback api

### ISSUE THREAD

**Issue by JonDum** [greensock/GreenSock-JS#93]
```
myAnimation.eventCallback("onComplete", myFunction, ["param1","param2"]);
```

I just realized how clunky this thing is. It also makes autoComplete fail. Is there any reason for such a clunky api? Why not just have actual functions with those names?
There's only five of them. Wouldn't affect filesize much "onComplete", "onUpdate", "onStart", "onReverseComplete" or "onRepeat".
```
myAnimation.onComplete(myFunction);
```

Much cleaner, no? It'd also be very, very nice if you could do this to normal tweens as well (tried adding it to `vars` object after a tween was created but that didn't work).

**Comment by jackdoyle** [comment]
I agree that your suggestion would make the API more intuitive, plus it'd help autocomplete kick in for convenience. If I remember correctly, the original purpose was to keep the API surface area as small as possible and keep the file size down. Let me chew on this a bit. Perhaps we'll add those 5 new methods.

**Comment by boyw165** [comment]
Hi Jack, it's so AWESOME that you write it all yourself.

**Comment by jackdoyle** [comment]
We haven't really looked into a Slack channel, no, but we do have some wonderful forums - the community there is great. http://greensock.com/forums/
