### ISSUE TITLE
Set Draggable position when using type = scroll 

### ISSUE THREAD

**Issue by naranjamecanica** [greensock/GreenSock-JS#94]
I'm looking for a way to set the position of the Draggable item when the type is "scroll". Because of the extra inserted element it feels a bit like an hack to acces that element. 

Is it an idea to handle it in the Draggable API?

    instance.setScrollPosition(x, y);

Or even better being able to animate to the position :+1: 

Again thanks for the great work on the js version!

**Comment by jackdoyle** [comment]
Sure, you can set it or animate it using the instance.scrollProxy.scrollTop() or scrollLeft() which serve as getters and setters. Is that what you're lookin' for?

**Comment by naranjamecanica** [comment]
Yes, perfect, thanks for the quick reply! 

Maybe an stupid question, knowing you're always on performance, but:

Does calling it like this:

        draggable.scrollProxy.scrollLeft(x);
        draggable.scrollProxy.scrollTop(y);

updates the DOM style attribute only once or twice? Because I could imagine using them in animation could add up otherwise.

**Comment by jackdoyle** [comment]
Nah, it's no different than what you'd have to do in vanilla JS anyway, setting the scrollLeft and then scrollTop. Performance-wise, that's not what hurts you - it's if you get/set/get/set (layout thrashing). Changing a style, then reading back a calculated style, then setting, etc., all within the same "tick".

**Comment by naranjamecanica** [comment]
Ok, thanks for the info.

One last thing is that I don't see a direct way to get the current dimensions, so i can check if an item in de dragger is on screen or not. Is this something you would add to the scrollproxy?

**Comment by jackdoyle** [comment]
Great :)
