### ISSUE TITLE
ThrowPropsPlugin does not support roundProps?

### ISSUE THREAD

**Issue by naranjamecanica** [greensock/GreenSock-JS#96]
Is it possible to do something like:

    ThrowPropsPlugin.to(positionObj, {
      throwProps: {
        x: {
           ...
        },
        y: {
            ...
        }
      },
      roundProps: 'x,y'
    });

It seems this does not work, right now i'm using the onUpdate to round the values myself.

**Comment by jackdoyle** [comment]
Hm, did you load RoundPropsPlugin?

**Comment by naranjamecanica** [comment]
I'm loading TweenMax which includes it, right? Or do I need to manually load it?

**Comment by jackdoyle** [comment]
Yep. Could you send me a demo of it not working? Perhaps a codepen? Seems to work for me: http://codepen.io/GreenSock/pen/bd86cb863bb015d8146d673debd3af62

**Comment by naranjamecanica** [comment]
I've found the issue, it does not work on directly objects?

The following does not work:

    var box = {x:0};

    TweenMax.to(box, 2, {throwProps:{x:300}, roundProps:"x", onUpdate:function() {
      console.log(box.x);
    }});

I'm animating an object who's properties I use later to move stuff around.

**Comment by naranjamecanica** [comment]
Is it correct that it doesn't work on basis objects? If so is this intended or a bug? Otherwise we can close this. Thanks.

**Comment by jackdoyle** [comment]
Sorry about that - I was immersed in a somewhat related feature/tool that I was trying to hammer out before responding here. You're absolutely right - it is supposed to work with regular objects; ThrowPropsPlugin was literally missing 3 characters on one line of code. My apologies. I just uploaded a new zip with the fix in place. Please let me know if that works well for you.

**Comment by naranjamecanica** [comment]
Sure no problem, if you only know how much time you saved me? :+1: 

I will test it tonight!

**Comment by naranjamecanica** [comment]
Works like a charm!

**Comment by jackdoyle** [comment]
Excellent. Glad to hear it. Thanks for reporting back.
