### ISSUE TITLE
Support for tweening that doesn't touch the DOM

### ISSUE THREAD

**Issue by thure** [greensock/GreenSock-JS#98]
During construction of a `TweenMax` instance, inevitably some DOM node needs to get involved, which doesn't seem strictly necessary and limits this library's potential usefulness. GSAP has the potential to work well in environments in which the DOM is unavailable (e.g. WebGL, Node).

Greensock should consider divorcing the mathematical tweening operations from DOM manipulation operations.

**Comment by thure** [comment]
I'd consider doing this myself and making a pull request, but since this isn't open source that isn't an option. I'll have to go my own way.

**Comment by jackdoyle** [comment]
I agree, and I'm a bit confused here - were you under the impression that GSAP is just for DOM manipulation? It's not at all - it can animate pretty much anything that JS can touch. Lots of people use it for WebGL, canvas, etc. Was there something in the code that gave you the impression that GSAP is strictly tied to the DOM? There are a few plugins that are tied to the DOM out of necessity, like CSSPlugin, but the core isn't (unless maybe I'm missing something that you saw).
